# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `faraday` gem.
# Please instead update this file by running `bin/tapioca gem faraday`.


# This is the main namespace for Faraday.
#
# It provides methods to create {Connection} objects, and HTTP-related
# methods to use directly.
#
# @example Helpful class method `.new` to create {Connection} objects.
#   conn = Faraday.new "http://faraday.com"
#   conn.get '/'
# @example Helpful class methods for easy usage
#   Faraday.get "http://faraday.com"
#
# pkg:gem/faraday#lib/faraday/middleware_registry.rb:5
module Faraday
  class << self
    # @overload default_adapter
    # @overload default_adapter=
    #
    # pkg:gem/faraday#lib/faraday.rb:62
    def default_adapter; end

    # Documented elsewhere, see default_adapter reader
    #
    # pkg:gem/faraday#lib/faraday.rb:118
    def default_adapter=(adapter); end

    # @overload default_connection
    # @overload default_connection=
    #
    # pkg:gem/faraday#lib/faraday.rb:136
    def default_connection; end

    # Documented below, see default_connection
    #
    # pkg:gem/faraday#lib/faraday.rb:65
    def default_connection=(_arg0); end

    # Gets the default connection options used when calling {Faraday#new}.
    #
    # @return [Faraday::ConnectionOptions]
    #
    # pkg:gem/faraday#lib/faraday.rb:143
    def default_connection_options; end

    # Sets the default options used when calling {Faraday#new}.
    #
    # @param options [Hash, Faraday::ConnectionOptions]
    #
    # pkg:gem/faraday#lib/faraday.rb:150
    def default_connection_options=(options); end

    # Tells Faraday to ignore the environment proxy (http_proxy).
    # Defaults to `false`.
    #
    # @return [Boolean]
    #
    # pkg:gem/faraday#lib/faraday.rb:70
    def ignore_env_proxy; end

    # Tells Faraday to ignore the environment proxy (http_proxy).
    # Defaults to `false`.
    #
    # @return [Boolean]
    #
    # pkg:gem/faraday#lib/faraday.rb:70
    def ignore_env_proxy=(_arg0); end

    # Gets or sets the path that the Faraday libs are loaded from.
    #
    # @return [String]
    #
    # pkg:gem/faraday#lib/faraday.rb:53
    def lib_path; end

    # Gets or sets the path that the Faraday libs are loaded from.
    #
    # @return [String]
    #
    # pkg:gem/faraday#lib/faraday.rb:53
    def lib_path=(_arg0); end

    # Initializes a new {Connection}.
    #
    # @example With an URL argument
    #   Faraday.new 'http://faraday.com'
    #   # => Faraday::Connection to http://faraday.com
    # @example With an URL argument and an options hash
    #   Faraday.new 'http://faraday.com', params: { page: 1 }
    #   # => Faraday::Connection to http://faraday.com?page=1
    # @example With everything in an options hash
    #   Faraday.new url: 'http://faraday.com',
    #   params: { page: 1 }
    #   # => Faraday::Connection to http://faraday.com?page=1
    # @option options
    # @option options
    # @option options
    # @option options
    # @option options
    # @option options
    # @param options [Hash]
    # @param url [String, Hash] The optional String base URL to use as a prefix
    #   for all requests.  Can also be the options Hash. Any of these
    #   values will be set on every request made, unless overridden
    #   for a specific request.
    # @return [Faraday::Connection]
    #
    # pkg:gem/faraday#lib/faraday.rb:99
    def new(url = T.unsafe(nil), options = T.unsafe(nil), &block); end

    # Internal: Requires internal Faraday libraries.
    #
    # @param libs [Array] one or more relative String names to Faraday classes.
    # @private
    # @return [void]
    #
    # pkg:gem/faraday#lib/faraday.rb:115
    def require_lib(*libs); end

    # Internal: Requires internal Faraday libraries.
    #
    # @param libs [Array] one or more relative String names to Faraday classes.
    # @private
    # @return [void]
    #
    # pkg:gem/faraday#lib/faraday.rb:109
    def require_libs(*libs); end

    # @return [Boolean]
    #
    # pkg:gem/faraday#lib/faraday.rb:123
    def respond_to_missing?(symbol, include_private = T.unsafe(nil)); end

    # The root path that Faraday is being loaded from.
    #
    # This is the root from where the libraries are auto-loaded.
    #
    # @return [String]
    #
    # pkg:gem/faraday#lib/faraday.rb:49
    def root_path; end

    # The root path that Faraday is being loaded from.
    #
    # This is the root from where the libraries are auto-loaded.
    #
    # @return [String]
    #
    # pkg:gem/faraday#lib/faraday.rb:49
    def root_path=(_arg0); end

    private

    # Internal: Proxies method calls on the Faraday constant to
    # .default_connection.
    #
    # pkg:gem/faraday#lib/faraday.rb:159
    def method_missing(name, *args, &block); end
  end
end

# Adapter is the base class for all Faraday adapters.
#
# @see lib/faraday/adapter.rb Original class location
#
# pkg:gem/faraday#lib/faraday/adapter.rb:6
class Faraday::Adapter
  extend ::Faraday::MiddlewareRegistry
  extend ::Faraday::DependencyLoader
  extend ::Faraday::Adapter::Parallelism
  extend ::Faraday::AutoloadHelper

  # @return [Adapter] a new instance of Adapter
  #
  # pkg:gem/faraday#lib/faraday/adapter.rb:44
  def initialize(_app = T.unsafe(nil), opts = T.unsafe(nil), &block); end

  # pkg:gem/faraday#lib/faraday/adapter.rb:71
  def call(env); end

  # Close any persistent connections. The adapter should still be usable
  # after calling close.
  #
  # pkg:gem/faraday#lib/faraday/adapter.rb:66
  def close; end

  # Yields or returns an adapter's configured connection. Depends on
  # #build_connection being defined on this adapter.
  #
  # @param env [Faraday::Env, Hash] The env object for a faraday request.
  # @return The return value of the given block, or the HTTP connection object
  #   if no block is given.
  # @yield [conn]
  #
  # pkg:gem/faraday#lib/faraday/adapter.rb:57
  def connection(env); end

  private

  # Fetches either a read, write, or open timeout setting. Defaults to the
  # :timeout value if a more specific one is not given.
  #
  # @param options [Hash] Hash containing Symbol keys like :timeout,
  #   :read_timeout, :write_timeout, :open_timeout, or
  #   :timeout
  # @param type [Symbol] Describes which timeout setting to get: :read,
  #   :write, or :open.
  # @return [Integer, nil] Timeout duration in seconds, or nil if no timeout
  #   has been set.
  #
  # pkg:gem/faraday#lib/faraday/adapter.rb:102
  def request_timeout(type, options); end

  # pkg:gem/faraday#lib/faraday/adapter.rb:78
  def save_response(env, status, body, headers = T.unsafe(nil), reason_phrase = T.unsafe(nil)); end
end

# pkg:gem/faraday#lib/faraday/adapter.rb:10
Faraday::Adapter::CONTENT_LENGTH = T.let(T.unsafe(nil), String)

# EventMachine adapter. This adapter is useful for either asynchronous
# requests when in an EM reactor loop, or for making parallel requests in
# synchronous code.
#
# pkg:gem/faraday#lib/faraday/adapter/em_http.rb:8
class Faraday::Adapter::EMHttp < ::Faraday::Adapter
  include ::Faraday::Adapter::EMHttp::Options

  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:116
  def call(env); end

  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:190
  def create_request(env); end

  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:196
  def error_message(client); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:220
  def parallel?(env); end

  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:122
  def perform_request(env); end

  # TODO: reuse the connection to support pipelining
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:168
  def perform_single_request(env); end

  # @raise [error_class]
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:200
  def raise_error(msg); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:214
  def timeout_message?(msg); end

  class << self
    # @return [Manager]
    #
    # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:112
    def setup_parallel_manager(_options = T.unsafe(nil)); end
  end
end

# This parallel manager is designed to start an EventMachine loop
# and block until all registered requests have been completed.
#
# pkg:gem/faraday#lib/faraday/adapter/em_http.rb:226
class Faraday::Adapter::EMHttp::Manager
  # @return [Manager] a new instance of Manager
  # @see reset
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:228
  def initialize; end

  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:246
  def add(&block); end

  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:283
  def check_finished; end

  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:271
  def perform_request; end

  # Re-initializes instance variables
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:233
  def reset; end

  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:255
  def run; end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:242
  def running?; end
end

# Options is a module containing helpers to convert the Faraday env object
# into options hashes for EMHTTP method calls.
#
# pkg:gem/faraday#lib/faraday/adapter/em_http.rb:11
module Faraday::Adapter::EMHttp::Options
  # Reads out compression header settings from env into options
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:79
  def configure_compression(options, env); end

  # Reads out proxy settings from env into options
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:39
  def configure_proxy(options, env); end

  # Reads out host and port settings from env into options
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:51
  def configure_socket(options, env); end

  # Reads out SSL certificate settings from env into options
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:62
  def configure_ssl(options, env); end

  # Reads out timeout settings from env into options
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:72
  def configure_timeout(options, env); end

  # @return [Hash]
  #
  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:13
  def connection_config(env); end

  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:33
  def read_body(env); end

  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:22
  def request_config(env); end

  # pkg:gem/faraday#lib/faraday/adapter/em_http.rb:86
  def request_options(env); end
end

# EventMachine Synchrony adapter.
#
# pkg:gem/faraday#lib/faraday/adapter/em_synchrony.rb:8
class Faraday::Adapter::EMSynchrony < ::Faraday::Adapter
  include ::Faraday::Adapter::EMHttp::Options

  # pkg:gem/faraday#lib/faraday/adapter/em_synchrony.rb:40
  def call(env); end

  # pkg:gem/faraday#lib/faraday/adapter/em_synchrony.rb:82
  def create_request(env); end

  private

  # pkg:gem/faraday#lib/faraday/adapter/em_synchrony.rb:135
  def call_block(block); end

  # pkg:gem/faraday#lib/faraday/adapter/em_synchrony.rb:91
  def execute_parallel_request(env, request, http_method); end

  # pkg:gem/faraday#lib/faraday/adapter/em_synchrony.rb:112
  def execute_single_request(env, request, http_method); end

  class << self
    # @return [ParallelManager]
    #
    # pkg:gem/faraday#lib/faraday/adapter/em_synchrony.rb:36
    def setup_parallel_manager(_options = T.unsafe(nil)); end
  end
end

# Excon adapter.
#
# pkg:gem/faraday#lib/faraday/adapter/excon.rb:6
class Faraday::Adapter::Excon < ::Faraday::Adapter
  # pkg:gem/faraday#lib/faraday/adapter/excon.rb:9
  def build_connection(env); end

  # pkg:gem/faraday#lib/faraday/adapter/excon.rb:14
  def call(env); end

  # TODO: support streaming requests
  #
  # pkg:gem/faraday#lib/faraday/adapter/excon.rb:47
  def read_body(env); end

  private

  # pkg:gem/faraday#lib/faraday/adapter/excon.rb:108
  def amend_opts_with_proxy_settings!(opts, req); end

  # pkg:gem/faraday#lib/faraday/adapter/excon.rb:81
  def amend_opts_with_ssl!(opts, ssl); end

  # pkg:gem/faraday#lib/faraday/adapter/excon.rb:94
  def amend_opts_with_timeouts!(opts, req); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter/excon.rb:65
  def needs_ssl_settings?(env); end

  # pkg:gem/faraday#lib/faraday/adapter/excon.rb:53
  def opts_from_env(env); end

  # pkg:gem/faraday#lib/faraday/adapter/excon.rb:112
  def proxy_settings_for_opts(proxy); end
end

# pkg:gem/faraday#lib/faraday/adapter/excon.rb:69
Faraday::Adapter::Excon::OPTS_KEYS = T.let(T.unsafe(nil), Array)

# HTTPClient adapter.
#
# pkg:gem/faraday#lib/faraday/adapter/httpclient.rb:6
class Faraday::Adapter::HTTPClient < ::Faraday::Adapter
  # pkg:gem/faraday#lib/faraday/adapter/httpclient.rb:9
  def build_connection(env); end

  # pkg:gem/faraday#lib/faraday/adapter/httpclient.rb:36
  def call(env); end

  # pkg:gem/faraday#lib/faraday/adapter/httpclient.rb:121
  def configure_client(client); end

  # Configure proxy URI and any user credentials.
  #
  # @param proxy [Hash]
  #
  # pkg:gem/faraday#lib/faraday/adapter/httpclient.rb:86
  def configure_proxy(client, proxy); end

  # @param bind [Hash]
  #
  # pkg:gem/faraday#lib/faraday/adapter/httpclient.rb:78
  def configure_socket(client, bind); end

  # @param ssl [Hash]
  #
  # pkg:gem/faraday#lib/faraday/adapter/httpclient.rb:94
  def configure_ssl(client, ssl); end

  # @param req [Hash]
  #
  # pkg:gem/faraday#lib/faraday/adapter/httpclient.rb:107
  def configure_timeouts(client, req); end

  # @param ssl [Hash]
  # @return [OpenSSL::X509::Store]
  #
  # pkg:gem/faraday#lib/faraday/adapter/httpclient.rb:127
  def ssl_cert_store(ssl); end

  # @param ssl [Hash]
  #
  # pkg:gem/faraday#lib/faraday/adapter/httpclient.rb:140
  def ssl_verify_mode(ssl); end
end

# Net::HTTP adapter.
#
# pkg:gem/faraday#lib/faraday/adapter/net_http.rb:15
class Faraday::Adapter::NetHttp < ::Faraday::Adapter
  # @return [NetHttp] a new instance of NetHttp
  #
  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:40
  def initialize(app = T.unsafe(nil), opts = T.unsafe(nil), &block); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:45
  def build_connection(env); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:67
  def call(env); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:55
  def net_http_connection(env); end

  private

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:180
  def configure_request(http, req); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:164
  def configure_ssl(http, ssl); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:96
  def create_request(env); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:112
  def perform_request(http, env); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:142
  def request_via_get_method(http, env, &block); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:150
  def request_via_request_method(http, env, &block); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:133
  def request_with_wrapped_block(http, env, &block); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:200
  def ssl_cert_store(ssl); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http.rb:209
  def ssl_verify_mode(ssl); end
end

# pkg:gem/faraday#lib/faraday/adapter/net_http.rb:38
Faraday::Adapter::NetHttp::NET_HTTP_EXCEPTIONS = T.let(T.unsafe(nil), Array)

# Net::HTTP::Persistent adapter.
#
# pkg:gem/faraday#lib/faraday/adapter/net_http_persistent.rb:6
class Faraday::Adapter::NetHttpPersistent < ::Faraday::Adapter::NetHttp
  private

  # pkg:gem/faraday#lib/faraday/adapter/net_http_persistent.rb:75
  def configure_ssl(http, ssl); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http_persistent.rb:86
  def http_set(http, attr, value); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http_persistent.rb:11
  def net_http_connection(env); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http_persistent.rb:52
  def perform_request(http, env); end

  # pkg:gem/faraday#lib/faraday/adapter/net_http_persistent.rb:31
  def proxy_uri(env); end
end

# pkg:gem/faraday#lib/faraday/adapter/net_http_persistent.rb:66
Faraday::Adapter::NetHttpPersistent::SSL_CONFIGURATIONS = T.let(T.unsafe(nil), Hash)

# This module marks an Adapter as supporting parallel requests.
#
# pkg:gem/faraday#lib/faraday/adapter.rb:28
module Faraday::Adapter::Parallelism
  # pkg:gem/faraday#lib/faraday/adapter.rb:35
  def inherited(subclass); end

  # Sets the attribute supports_parallel
  #
  # @param value the value to set the attribute supports_parallel to.
  #
  # pkg:gem/faraday#lib/faraday/adapter.rb:29
  def supports_parallel=(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter.rb:31
  def supports_parallel?; end
end

# Patron adapter.
#
# pkg:gem/faraday#lib/faraday/adapter/patron.rb:6
class Faraday::Adapter::Patron < ::Faraday::Adapter
  # pkg:gem/faraday#lib/faraday/adapter/patron.rb:9
  def build_connection(env); end

  # pkg:gem/faraday#lib/faraday/adapter/patron.rb:24
  def call(env); end

  # pkg:gem/faraday#lib/faraday/adapter/patron.rb:101
  def configure_proxy(session, proxy); end

  # pkg:gem/faraday#lib/faraday/adapter/patron.rb:81
  def configure_ssl(session, ssl); end

  # pkg:gem/faraday#lib/faraday/adapter/patron.rb:89
  def configure_timeouts(session, req); end

  private

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter/patron.rb:125
  def connection_timed_out_message?(message); end
end

# pkg:gem/faraday#lib/faraday/adapter/patron.rb:114
Faraday::Adapter::Patron::CURL_TIMEOUT_MESSAGES = T.let(T.unsafe(nil), Array)

# Sends requests to a Rack app.
#
# @example
#
#   class MyRackApp
#   def call(env)
#   [200, {'Content-Type' => 'text/html'}, ["hello world"]]
#   end
#   end
#
#   Faraday.new do |conn|
#   conn.adapter :rack, MyRackApp.new
#   end
#
# pkg:gem/faraday#lib/faraday/adapter/rack.rb:18
class Faraday::Adapter::Rack < ::Faraday::Adapter
  # @return [Rack] a new instance of Rack
  #
  # pkg:gem/faraday#lib/faraday/adapter/rack.rb:24
  def initialize(faraday_app, rack_app); end

  # pkg:gem/faraday#lib/faraday/adapter/rack.rb:30
  def call(env); end

  private

  # pkg:gem/faraday#lib/faraday/adapter/rack.rb:66
  def build_rack_env(env); end

  # pkg:gem/faraday#lib/faraday/adapter/rack.rb:62
  def execute_request(env, rack_env); end
end

# not prefixed with "HTTP_"
#
# pkg:gem/faraday#lib/faraday/adapter/rack.rb:22
Faraday::Adapter::Rack::SPECIAL_HEADERS = T.let(T.unsafe(nil), Array)

# pkg:gem/faraday#lib/faraday/adapter.rb:110
Faraday::Adapter::TIMEOUT_KEYS = T.let(T.unsafe(nil), Hash)

# @example
#   test = Faraday::Connection.new do
#   use Faraday::Adapter::Test do |stub|
#   # Define matcher to match the request
#   stub.get '/resource.json' do
#   # return static content
#   [200, {'Content-Type' => 'application/json'}, 'hi world']
#   end
#
#   # response with content generated based on request
#   stub.get '/showget' do |env|
#   [200, {'Content-Type' => 'text/plain'}, env[:method].to_s]
#   end
#
#   # A regular expression can be used as matching filter
#   stub.get /\A\/items\/(\d+)\z/ do |env, meta|
#   # in case regular expression is used, an instance of MatchData
#   # can be received
#   [200,
#   {'Content-Type' => 'text/plain'},
#   "showing item: #{meta[:match_data][1]}"
#   ]
#   end
#   end
#   end
#
#   resp = test.get '/resource.json'
#   resp.body # => 'hi world'
#
#   resp = test.get '/showget'
#   resp.body # => 'get'
#
#   resp = test.get '/items/1'
#   resp.body # => 'showing item: 1'
#
#   resp = test.get '/items/2'
#   resp.body # => 'showing item: 2'
#
# pkg:gem/faraday#lib/faraday/adapter/test.rb:42
class Faraday::Adapter::Test < ::Faraday::Adapter
  # @return [Test] a new instance of Test
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:203
  def initialize(app, stubs = T.unsafe(nil), &block); end

  # pkg:gem/faraday#lib/faraday/adapter/test.rb:213
  def call(env); end

  # @yield [stubs]
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:209
  def configure; end

  # Returns the value of attribute stubs.
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:43
  def stubs; end

  # Sets the attribute stubs
  #
  # @param value the value to set the attribute stubs to.
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:43
  def stubs=(_arg0); end
end

# Stub request
#
# pkg:gem/faraday#lib/faraday/adapter/test.rb:146
class Faraday::Adapter::Test::Stub < ::Struct
  # @return [Stub] a new instance of Stub
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:148
  def initialize(host, full, headers, body, block); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:192
  def headers_match?(request_headers); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:160
  def matches?(request_host, request_uri, request_headers, request_body); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:186
  def params_match?(request_params); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:178
  def path_match?(request_path, meta); end

  # pkg:gem/faraday#lib/faraday/adapter/test.rb:198
  def to_s; end
end

# A stack of Stubs
#
# pkg:gem/faraday#lib/faraday/adapter/test.rb:46
class Faraday::Adapter::Test::Stubs
  # @return [Stubs] a new instance of Stubs
  # @yield [_self]
  # @yieldparam _self [Faraday::Adapter::Test::Stubs] the object that the method was called on
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:50
  def initialize; end

  # pkg:gem/faraday#lib/faraday/adapter/test.rb:95
  def delete(path, headers = T.unsafe(nil), &block); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:57
  def empty?; end

  # pkg:gem/faraday#lib/faraday/adapter/test.rb:75
  def get(path, headers = T.unsafe(nil), &block); end

  # pkg:gem/faraday#lib/faraday/adapter/test.rb:79
  def head(path, headers = T.unsafe(nil), &block); end

  # pkg:gem/faraday#lib/faraday/adapter/test.rb:61
  def match(request_method, host, path, headers, body); end

  # pkg:gem/faraday#lib/faraday/adapter/test.rb:99
  def options(path, headers = T.unsafe(nil), &block); end

  # pkg:gem/faraday#lib/faraday/adapter/test.rb:91
  def patch(path, body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # pkg:gem/faraday#lib/faraday/adapter/test.rb:83
  def post(path, body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # pkg:gem/faraday#lib/faraday/adapter/test.rb:87
  def put(path, body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # Raises an error if any of the stubbed calls have not been made.
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:104
  def verify_stubbed_calls; end

  protected

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/adapter/test.rb:135
  def matches?(stack, host, path, headers, body); end

  # pkg:gem/faraday#lib/faraday/adapter/test.rb:120
  def new_stub(request_method, path, headers = T.unsafe(nil), body = T.unsafe(nil), &block); end
end

# pkg:gem/faraday#lib/faraday/adapter/test.rb:47
class Faraday::Adapter::Test::Stubs::NotFound < ::StandardError; end

# Typhoeus adapter. This class is just a stub, the real adapter is in
# https://github.com/typhoeus/typhoeus/blob/master/lib/typhoeus/adapters/faraday.rb
#
# pkg:gem/faraday#lib/faraday/adapter/typhoeus.rb:7
class Faraday::Adapter::Typhoeus < ::Faraday::Adapter
  # Needs to define this method in order to support Typhoeus <= 1.3.0
  #
  # pkg:gem/faraday#lib/faraday/adapter/typhoeus.rb:9
  def call; end
end

# AdapterRegistry registers adapter class names so they can be looked up by a
# String or Symbol name.
#
# pkg:gem/faraday#lib/faraday/adapter_registry.rb:8
class Faraday::AdapterRegistry
  # @return [AdapterRegistry] a new instance of AdapterRegistry
  #
  # pkg:gem/faraday#lib/faraday/adapter_registry.rb:9
  def initialize; end

  # pkg:gem/faraday#lib/faraday/adapter_registry.rb:14
  def get(name); end

  # pkg:gem/faraday#lib/faraday/adapter_registry.rb:23
  def set(klass, name = T.unsafe(nil)); end
end

# Adds the ability for other modules to manage autoloadable
# constants.
#
# @api private
#
# pkg:gem/faraday#lib/faraday/autoload.rb:8
module Faraday::AutoloadHelper
  # Filters the module's contents with those that have been already
  # autoloaded.
  #
  # @api private
  # @return [Array<Class, Module>]
  #
  # pkg:gem/faraday#lib/faraday/autoload.rb:49
  def all_loaded_constants; end

  # Registers the constants to be auto loaded.
  #
  # @api private
  # @example
  #
  #   Faraday.autoload_all 'faraday/foo',
  #   Bar: 'bar'
  #
  #   # requires faraday/foo/bar to load Faraday::Bar.
  #   Faraday::Bar
  # @param options [{ Symbol => String }] library names.
  # @param prefix [String] The require prefix. If the path is inside Faraday,
  #   then it will be prefixed with the root path of this loaded
  #   Faraday version.
  # @return [void]
  #
  # pkg:gem/faraday#lib/faraday/autoload.rb:25
  def autoload_all(prefix, options); end

  # Loads each autoloaded constant.  If thread safety is a concern,
  # wrap this in a Mutex.
  #
  # @api private
  # @return [void]
  #
  # pkg:gem/faraday#lib/faraday/autoload.rb:39
  def load_autoloaded_constants; end
end

# Raised by Faraday::Response::RaiseError in case of a 400 response.
#
# pkg:gem/faraday#lib/faraday/error.rb:77
class Faraday::BadRequestError < ::Faraday::ClientError; end

# Faraday client error class. Represents 4xx status responses.
#
# pkg:gem/faraday#lib/faraday/error.rb:73
class Faraday::ClientError < ::Faraday::Error; end

# Similar to, but not compatible with CompositeReadIO provided by the
# multipart-post gem.
# https://github.com/nicksieger/multipart-post/blob/master/lib/composite_io.rb
#
# pkg:gem/faraday#lib/faraday/file_part.rb:66
class Faraday::CompositeReadIO
  # @return [CompositeReadIO] a new instance of CompositeReadIO
  #
  # pkg:gem/faraday#lib/faraday/file_part.rb:67
  def initialize(*parts); end

  # Close each of the IOs.
  #
  # @return [void]
  #
  # pkg:gem/faraday#lib/faraday/file_part.rb:110
  def close; end

  # pkg:gem/faraday#lib/faraday/file_part.rb:114
  def ensure_open_and_readable; end

  # @return [Integer] sum of the lengths of all the parts
  #
  # pkg:gem/faraday#lib/faraday/file_part.rb:74
  def length; end

  # Read from IOs in order until `length` bytes have been received.
  #
  # @param length [Integer, nil]
  # @param outbuf [String, nil]
  #
  # pkg:gem/faraday#lib/faraday/file_part.rb:90
  def read(length = T.unsafe(nil), outbuf = T.unsafe(nil)); end

  # Rewind each of the IOs and reset the index to 0.
  #
  # @return [void]
  #
  # pkg:gem/faraday#lib/faraday/file_part.rb:81
  def rewind; end

  private

  # pkg:gem/faraday#lib/faraday/file_part.rb:124
  def advance_io; end

  # pkg:gem/faraday#lib/faraday/file_part.rb:120
  def current_io; end
end

# Raised by Faraday::Response::RaiseError in case of a 409 response.
#
# pkg:gem/faraday#lib/faraday/error.rb:97
class Faraday::ConflictError < ::Faraday::ClientError; end

# Connection objects manage the default properties and the middleware
# stack for fulfilling an HTTP request.
#
# @example
#
#   conn = Faraday::Connection.new 'http://sushi.com'
#
#   # GET http://sushi.com/nigiri
#   conn.get 'nigiri'
#   # => #<Faraday::Response>
#
# pkg:gem/faraday#lib/faraday/connection.rb:15
class Faraday::Connection
  extend ::Forwardable

  # Initializes a new Faraday::Connection.
  #
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @param options [Hash, Faraday::ConnectionOptions]
  # @param url [URI, String] URI or String base URL to use as a prefix for all
  #   requests (optional).
  # @return [Connection] a new instance of Connection
  # @yield [self] after all setup has been done
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:62
  def initialize(url = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/connection.rb:118
  def adapter(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/connection.rb:118
  def app(*args, **_arg1, &block); end

  # Sets up a custom Authorization header.
  #
  # @example
  #
  #   conn.authorization :Bearer, 'mF_9.B5f-4.1JqM'
  #   conn.headers['Authorization']
  #   # => "Bearer mF_9.B5f-4.1JqM"
  #
  #   conn.authorization :Token, token: 'abcdef', foo: 'bar'
  #   conn.headers['Authorization']
  #   # => "Token token=\"abcdef\",
  #   foo=\"bar\""
  # @param token [String, Hash] token. A String value is taken literally, and
  #   a Hash is encoded into comma-separated key/value pairs.
  # @param type [String] authorization type
  # @return [void]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:336
  def authorization(type, token); end

  # Sets up the Authorization header with these credentials, encoded
  # with base64.
  #
  # @example
  #
  #   conn.basic_auth 'Aladdin', 'open sesame'
  #   conn.headers['Authorization']
  #   # => "Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ=="
  # @param login [String] The authentication login.
  # @param pass [String] The authentication password.
  # @return [void]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:297
  def basic_auth(login, pass); end

  # pkg:gem/faraday#lib/faraday/connection.rb:118
  def build(*args, **_arg1, &block); end

  # Build an absolute URL based on url_prefix.
  #
  #          of the resulting url (default: nil).
  #
  # @param params [Faraday::Utils::ParamsHash] A Faraday::Utils::ParamsHash to
  #   replace the query values
  # @param url [String, URI]
  # @return [URI]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:518
  def build_exclusive_url(url = T.unsafe(nil), params = T.unsafe(nil), params_encoder = T.unsafe(nil)); end

  # Creates and configures the request object.
  #
  # @param method [Symbol]
  # @return [Faraday::Request]
  # @yield [Faraday::Request] if block given
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:501
  def build_request(method); end

  # Takes a relative url for a request and combines it with the defaults
  # set on the connection instance.
  #
  # @example
  #   conn = Faraday::Connection.new { ... }
  #   conn.url_prefix = "https://sushi.com/api?token=abc"
  #   conn.scheme      # => https
  #   conn.path_prefix # => "/api"
  #
  #   conn.build_url("nigiri?page=2")
  #   # => https://sushi.com/api/nigiri?token=abc&page=2
  #
  #   conn.build_url("nigiri", page: 2)
  #   # => https://sushi.com/api/nigiri?token=abc&page=2
  # @param extra_params [Hash]
  # @param url [String]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:455
  def build_url(url = T.unsafe(nil), extra_params = T.unsafe(nil)); end

  # @return [Faraday::Builder] Builder for this Connection.
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:30
  def builder; end

  # Closes the underlying resources and/or connections. In the case of
  # persistent connections, this closes all currently open connections
  # but does not prevent new connections from being made.
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:123
  def close; end

  # Check if the adapter is parallel-capable.
  #
  # @api private
  # @return [Object, nil] a parallel manager or nil if yielded
  # @yield if the adapter isn't parallel-capable, or if no adapter is set yet.
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:346
  def default_parallel_manager; end

  # Sets the default parallel manager for this connection.
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:39
  def default_parallel_manager=(_arg0); end

  # pkg:gem/faraday#lib/faraday/connection.rb:196
  def delete(url = T.unsafe(nil), params = T.unsafe(nil), headers = T.unsafe(nil)); end

  # Creates a duplicate of this Faraday::Connection.
  #
  # @api private
  # @return [Faraday::Connection]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:540
  def dup; end

  # pkg:gem/faraday#lib/faraday/connection.rb:592
  def find_default_proxy; end

  # pkg:gem/faraday#lib/faraday/connection.rb:196
  def get(url = T.unsafe(nil), params = T.unsafe(nil), headers = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/connection.rb:196
  def head(url = T.unsafe(nil), params = T.unsafe(nil), headers = T.unsafe(nil)); end

  # @return [Hash] unencoded HTTP header key/value pairs.
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:23
  def headers; end

  # Sets the Hash of unencoded HTTP header key/value pairs.
  #
  # @param hash [Hash]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:112
  def headers=(hash); end

  # pkg:gem/faraday#lib/faraday/connection.rb:393
  def host(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/connection.rb:393
  def host=(*args, **_arg1, &block); end

  # Sets up the parallel manager to make a set of requests.
  #
  # @param manager [Object] The parallel manager that this Connection's
  #   Adapter uses.
  # @return [void]
  # @yield a block to execute multiple requests.
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:372
  def in_parallel(manager = T.unsafe(nil)); end

  # Determine if this Faraday::Connection can make parallel requests.
  #
  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:361
  def in_parallel?; end

  # pkg:gem/faraday#lib/faraday/connection.rb:94
  def initialize_proxy(url, options); end

  # @example
  #   conn.options '/items/1'
  # @overload options
  # @overload options
  # @return [Faraday::Response]
  # @yield [Faraday::Request] for further request customizations
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:220
  def options(*args); end

  # @return [Object] the parallel manager for this Connection.
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:36
  def parallel_manager; end

  # @return [Hash] URI query unencoded key/value pairs.
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:20
  def params; end

  # Sets the Hash of URI query unencoded key/value pairs.
  #
  # @param hash [Hash]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:106
  def params=(hash); end

  # pkg:gem/faraday#lib/faraday/connection.rb:277
  def patch(url = T.unsafe(nil), body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # pkg:gem/faraday#lib/faraday/connection.rb:394
  def path_prefix(*args, **_arg1, &block); end

  # Sets the path prefix and ensures that it always has a leading
  # slash.
  #
  # @param value [String]
  # @return [String] the new path prefix
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:430
  def path_prefix=(value); end

  # pkg:gem/faraday#lib/faraday/connection.rb:393
  def port(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/connection.rb:393
  def port=(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/connection.rb:277
  def post(url = T.unsafe(nil), body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # @return [Hash] proxy options.
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:42
  def proxy; end

  # Sets the Hash proxy options.
  #
  # @param new_value [Object]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:388
  def proxy=(new_value); end

  # pkg:gem/faraday#lib/faraday/connection.rb:600
  def proxy_for_request(url); end

  # pkg:gem/faraday#lib/faraday/connection.rb:571
  def proxy_from_env(url); end

  # pkg:gem/faraday#lib/faraday/connection.rb:277
  def put(url = T.unsafe(nil), body = T.unsafe(nil), headers = T.unsafe(nil), &block); end

  # pkg:gem/faraday#lib/faraday/connection.rb:118
  def request(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/connection.rb:118
  def response(*args, **_arg1, &block); end

  # Builds and runs the Faraday::Request.
  #
  # @param body [Object] The request body that will eventually be converted to
  #   a string.
  # @param headers [Hash] unencoded HTTP header key/value pairs.
  # @param method [Symbol] HTTP method.
  # @param url [String, URI] String or URI to access.
  # @return [Faraday::Response]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:479
  def run_request(method, url, body, headers); end

  # pkg:gem/faraday#lib/faraday/connection.rb:393
  def scheme(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/connection.rb:393
  def scheme=(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/connection.rb:563
  def set_authorization_header(header_type, *args); end

  # @return [Hash] SSL options.
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:33
  def ssl; end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:610
  def support_parallel?(adapter); end

  # Sets up the Authorization header with the given token.
  #
  # @example
  #
  #   conn.token_auth 'abcdef', foo: 'bar'
  #   conn.headers['Authorization']
  #   # => "Token token=\"abcdef\",
  #   foo=\"bar\""
  # @param options [Hash] extra token options.
  # @param token [String]
  # @return [void]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:314
  def token_auth(token, options = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/connection.rb:196
  def trace(url = T.unsafe(nil), params = T.unsafe(nil), headers = T.unsafe(nil)); end

  # @return [String] a URI with the prefix used for all requests from this
  #   Connection. This includes a default host name, scheme, port, and path.
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:27
  def url_prefix; end

  # Parses the given URL with URI and stores the individual
  # components in this connection. These components serve as defaults for
  # requests made by this connection.
  #
  # @example
  #
  #   conn = Faraday::Connection.new { ... }
  #   conn.url_prefix = "https://sushi.com/api"
  #   conn.scheme      # => https
  #   conn.path_prefix # => "/api"
  #
  #   conn.get("nigiri?page=2") # accesses https://sushi.com/api/nigiri
  # @param encoder [Object]
  # @param url [String, URI]
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:411
  def url_prefix=(url, encoder = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/connection.rb:118
  def use(*args, **_arg1, &block); end

  # Yields username and password extracted from a URI if they both exist.
  #
  # @api private
  # @param uri [URI]
  # @return [void]
  # @yield [username, password] any username and password
  # @yieldparam password [String] any password from URI
  # @yieldparam username [String] any username from URI
  #
  # pkg:gem/faraday#lib/faraday/connection.rb:557
  def with_uri_credentials(uri); end
end

# A Set of allowed HTTP verbs.
#
# pkg:gem/faraday#lib/faraday/connection.rb:17
Faraday::Connection::METHODS = T.let(T.unsafe(nil), Set)

# A unified error for failed connections.
#
# pkg:gem/faraday#lib/faraday/error.rb:124
class Faraday::ConnectionFailed < ::Faraday::Error; end

# ConnectionOptions contains the configurable properties for a Faraday
# connection object.
#
# pkg:gem/faraday#lib/faraday/options/connection_options.rb:8
class Faraday::ConnectionOptions < ::Faraday::Options
  # pkg:gem/faraday#lib/faraday/options/connection_options.rb:16
  def builder_class; end

  # pkg:gem/faraday#lib/faraday/options/connection_options.rb:18
  def new_builder(block); end

  # pkg:gem/faraday#lib/faraday/options/connection_options.rb:12
  def request; end

  # pkg:gem/faraday#lib/faraday/options/connection_options.rb:14
  def ssl; end
end

# Sub-module for decoding query-string into parameters.
#
# pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:75
module Faraday::DecodeMethods
  # @param query [nil, String]
  # @raise [TypeError] if the nesting is incorrect
  # @return [Array<Array, String>] the decoded params
  #
  # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:81
  def decode(query); end

  protected

  # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:138
  def add_to_context(is_array, context, value, subkey); end

  # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:101
  def decode_pair(key, value, context); end

  # Internal: convert a nested hash with purely numeric keys into an array.
  # FIXME: this is not compatible with Rack::Utils.parse_nested_query
  #
  # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:145
  def dehash(hash, depth); end

  # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:133
  def match_context(context, subkey); end

  # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:123
  def new_context(subkey, is_array, context); end

  # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:113
  def prepare_context(context, subkey, is_array, last_subkey); end
end

# pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:99
Faraday::DecodeMethods::SUBKEYS_REGEX = T.let(T.unsafe(nil), Regexp)

# DependencyLoader helps Faraday adapters and middleware load dependencies.
#
# pkg:gem/faraday#lib/faraday/dependency_loader.rb:5
module Faraday::DependencyLoader
  # Executes a block which should try to require and reference dependent
  # libraries
  #
  # pkg:gem/faraday#lib/faraday/dependency_loader.rb:10
  def dependency(lib = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/dependency_loader.rb:28
  def inherited(subclass); end

  # Returns the value of attribute load_error.
  #
  # pkg:gem/faraday#lib/faraday/dependency_loader.rb:6
  def load_error; end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/dependency_loader.rb:24
  def loaded?; end

  # pkg:gem/faraday#lib/faraday/dependency_loader.rb:16
  def new(*_arg0); end

  private

  # Sets the attribute load_error
  #
  # @param value the value to set the attribute load_error to.
  #
  # pkg:gem/faraday#lib/faraday/dependency_loader.rb:35
  def load_error=(_arg0); end
end

# Sub-module for encoding parameters into query-string.
#
# pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:5
module Faraday::EncodeMethods
  # @param params [nil, Array, #to_hash] parameters to be encoded
  # @raise [TypeError] if params can not be converted to a Hash
  # @return [String] the encoded params
  #
  # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:11
  def encode(params); end

  protected

  # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:64
  def encode_array(parent, value); end

  # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:53
  def encode_hash(parent, value); end

  # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:40
  def encode_pair(parent, value); end
end

# pkg:gem/faraday#lib/faraday/options/env.rb:52
class Faraday::Env < ::Faraday::Options
  extend ::Forwardable

  # @param key [Object]
  #
  # pkg:gem/faraday#lib/faraday/options/env.rb:84
  def [](key); end

  # @param key [Object]
  # @param value [Object]
  #
  # pkg:gem/faraday#lib/faraday/options/env.rb:96
  def []=(key, value); end

  # string.
  #
  # @return [String] The request body that will eventually be converted to a
  #
  # pkg:gem/faraday#lib/faraday/options/env.rb:113
  def body; end

  # string.
  #
  # @return [String] The request body that will eventually be converted to a
  #
  # pkg:gem/faraday#lib/faraday/options/env.rb:117
  def body=(value); end

  # Sets content length to zero and the body to the empty string.
  #
  # pkg:gem/faraday#lib/faraday/options/env.rb:133
  def clear_body; end

  # pkg:gem/faraday#lib/faraday/options/env.rb:109
  def current_body; end

  # @private
  #
  # pkg:gem/faraday#lib/faraday/options/env.rb:161
  def custom_members; end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/options/env.rb:167
  def in_member_set?(key); end

  # pkg:gem/faraday#lib/faraday/options/env.rb:149
  def inspect; end

  # set of {MethodsWithBodies}.
  #
  # @return [Boolean] true if there's no body yet, and the method is in the
  #
  # pkg:gem/faraday#lib/faraday/options/env.rb:128
  def needs_body?; end

  # @return [Boolean] true if there is a parallel_manager
  #
  # pkg:gem/faraday#lib/faraday/options/env.rb:145
  def parallel?; end

  # pkg:gem/faraday#lib/faraday/options/env.rb:69
  def params_encoder(*args, **_arg1, &block); end

  # {StatusesWithoutBody}.
  #
  # @return [Boolean] true if the status isn't in the set of
  #
  # pkg:gem/faraday#lib/faraday/options/env.rb:140
  def parse_body?; end

  # @return [Boolean] true if status is in the set of {SuccessfulStatuses}.
  #
  # pkg:gem/faraday#lib/faraday/options/env.rb:122
  def success?; end

  class << self
    # Build a new Env from given value. Respects and updates `custom_members`.
    #
    # @param value [Object] a value fitting Option.from(v).
    # @return [Env] from given value
    #
    # pkg:gem/faraday#lib/faraday/options/env.rb:75
    def from(value); end

    # @private
    #
    # pkg:gem/faraday#lib/faraday/options/env.rb:177
    def member_set; end
  end
end

# pkg:gem/faraday#lib/faraday/options/env.rb:55
Faraday::Env::ContentLength = T.let(T.unsafe(nil), String)

# A Set of HTTP verbs that typically send a body.  If no body is set for
# these requests, the Content-Length header is set to 0.
#
# pkg:gem/faraday#lib/faraday/options/env.rb:62
Faraday::Env::MethodsWithBodies = T.let(T.unsafe(nil), Set)

# pkg:gem/faraday#lib/faraday/options/env.rb:56
Faraday::Env::StatusesWithoutBody = T.let(T.unsafe(nil), Set)

# pkg:gem/faraday#lib/faraday/options/env.rb:57
Faraday::Env::SuccessfulStatuses = T.let(T.unsafe(nil), Range)

# Faraday error base class.
#
# pkg:gem/faraday#lib/faraday/error.rb:6
class Faraday::Error < ::StandardError
  # @return [Error] a new instance of Error
  #
  # pkg:gem/faraday#lib/faraday/error.rb:9
  def initialize(exc, response = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/error.rb:15
  def backtrace; end

  # pkg:gem/faraday#lib/faraday/error.rb:23
  def inspect; end

  # Returns the value of attribute response.
  #
  # pkg:gem/faraday#lib/faraday/error.rb:7
  def response; end

  # Returns the value of attribute wrapped_exception.
  #
  # pkg:gem/faraday#lib/faraday/error.rb:7
  def wrapped_exception; end

  protected

  # Pulls out potential parent exception and response hash.
  #
  # pkg:gem/faraday#lib/faraday/error.rb:62
  def exc_msg_and_response(exc, response = T.unsafe(nil)); end

  # Pulls out potential parent exception and response hash, storing them in
  # instance variables.
  # exc      - Either an Exception, a string message, or a response hash.
  # response - Hash
  #              :status  - Optional integer HTTP response status
  #              :headers - String key/value hash of HTTP response header
  #                         values.
  #              :body    - Optional string HTTP response body.
  #              :request - Hash
  #                           :method   - Symbol with the request HTTP method.
  #                           :url_path - String with the url path requested.
  #                           :params   - String key/value hash of query params
  #                                     present in the request.
  #                           :headers  - String key/value hash of HTTP request
  #                                     header values.
  #                           :body     - String HTTP request body.
  #
  # If a subclass has to call this, then it should pass a string message
  # to `super`. See NilStatusError.
  #
  # pkg:gem/faraday#lib/faraday/error.rb:52
  def exc_msg_and_response!(exc, response = T.unsafe(nil)); end
end

# The uploaded binary data's content type.
#
# The base filename, taken either from the filename_or_io or filename
# arguments in #initialize.
#
# Extra String key/value pairs to make up the header for this uploaded file.
#
# The open IO object for the uploaded file.
#
# @return [Faraday::FilePart]
# @return [String]
# @return [String]
# @return [Hash]
# @return [IO]
#
# pkg:gem/faraday#lib/faraday/file_part.rb:53
Faraday::FilePart = Multipart::Post::UploadIO

# FlatParamsEncoder manages URI params as a flat hash. Any Array values repeat
# the parameter multiple times.
#
# pkg:gem/faraday#lib/faraday/encoders/flat_params_encoder.rb:6
module Faraday::FlatParamsEncoder
  class << self
    # Decode converts the given URI querystring into a hash.
    #
    # @example
    #
    #   decode('a=one&a=two&a=three&b=true&c=C')
    #   # => {"a"=>["one", "two", "three"], "b"=>"true", "c"=>"C"}
    # @param query [String] query arguments to parse.
    # @return [Hash] parsed keys and value strings from the querystring.
    #
    # pkg:gem/faraday#lib/faraday/encoders/flat_params_encoder.rb:74
    def decode(query); end

    # Encode converts the given param into a URI querystring. Keys and values
    # will converted to strings and appropriately escaped for the URI.
    #
    # @example
    #
    #   encode({a: %w[one two three], b: true, c: "C"})
    #   # => 'a=one&a=two&a=three&b=true&c=C'
    # @param params [Hash] query arguments to convert.
    # @return [String] the URI querystring (without the leading '?')
    #
    # pkg:gem/faraday#lib/faraday/encoders/flat_params_encoder.rb:23
    def encode(params); end

    # pkg:gem/faraday#lib/faraday/encoders/flat_params_encoder.rb:9
    def escape(*args, **_arg1, &block); end

    # Returns the value of attribute sort_params.
    #
    # pkg:gem/faraday#lib/faraday/encoders/flat_params_encoder.rb:99
    def sort_params; end

    # Sets the attribute sort_params
    #
    # @param value the value to set the attribute sort_params to.
    #
    # pkg:gem/faraday#lib/faraday/encoders/flat_params_encoder.rb:99
    def sort_params=(_arg0); end

    # pkg:gem/faraday#lib/faraday/encoders/flat_params_encoder.rb:9
    def unescape(*args, **_arg1, &block); end
  end
end

# Raised by Faraday::Response::RaiseError in case of a 403 response.
#
# pkg:gem/faraday#lib/faraday/error.rb:85
class Faraday::ForbiddenError < ::Faraday::ClientError; end

# pkg:gem/faraday#lib/faraday/logging/formatter.rb:5
module Faraday::Logging; end

# Serves as an integration point to customize logging
#
# pkg:gem/faraday#lib/faraday/logging/formatter.rb:7
class Faraday::Logging::Formatter
  extend ::Forwardable

  # @return [Formatter] a new instance of Formatter
  #
  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:13
  def initialize(logger:, options:); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:19
  def debug(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:19
  def error(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:19
  def fatal(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:39
  def filter(filter_word, filter_replacement); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:19
  def info(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:21
  def request(env); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:31
  def response(env); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:19
  def warn(*args, **_arg1, &block); end

  private

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:79
  def apply_filters(output); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:49
  def dump_body(body); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:45
  def dump_headers(headers); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:99
  def log_body(type, body); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:70
  def log_body?(type); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:94
  def log_headers(type, headers); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:61
  def log_headers?(type); end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:86
  def log_level; end

  # pkg:gem/faraday#lib/faraday/logging/formatter.rb:57
  def pretty_inspect(body); end
end

# pkg:gem/faraday#lib/faraday/logging/formatter.rb:10
Faraday::Logging::Formatter::DEFAULT_OPTIONS = T.let(T.unsafe(nil), Hash)

# pkg:gem/faraday#lib/faraday/methods.rb:5
Faraday::METHODS_WITH_BODY = T.let(T.unsafe(nil), Array)

# pkg:gem/faraday#lib/faraday/methods.rb:4
Faraday::METHODS_WITH_QUERY = T.let(T.unsafe(nil), Array)

# Middleware is the basic base class of any Faraday middleware.
#
# pkg:gem/faraday#lib/faraday/middleware.rb:5
class Faraday::Middleware
  extend ::Faraday::MiddlewareRegistry
  extend ::Faraday::DependencyLoader

  # @return [Middleware] a new instance of Middleware
  #
  # pkg:gem/faraday#lib/faraday/middleware.rb:11
  def initialize(app = T.unsafe(nil), options = T.unsafe(nil)); end

  # Returns the value of attribute app.
  #
  # pkg:gem/faraday#lib/faraday/middleware.rb:9
  def app; end

  # pkg:gem/faraday#lib/faraday/middleware.rb:16
  def call(env); end

  # pkg:gem/faraday#lib/faraday/middleware.rb:23
  def close; end

  # Returns the value of attribute options.
  #
  # pkg:gem/faraday#lib/faraday/middleware.rb:9
  def options; end
end

# Adds the ability for other modules to register and lookup
# middleware classes.
#
# pkg:gem/faraday#lib/faraday/middleware_registry.rb:8
module Faraday::MiddlewareRegistry
  # pkg:gem/faraday#lib/faraday/middleware_registry.rb:99
  def fetch_middleware(key); end

  # pkg:gem/faraday#lib/faraday/middleware_registry.rb:103
  def load_middleware(key); end

  # Lookup middleware class with a registered Symbol shortcut.
  #
  # @example
  #
  #   module Faraday
  #   class Whatever
  #   register_middleware foo: Foo
  #   end
  #   end
  #
  #   Faraday::Whatever.lookup_middleware(:foo)
  #   # => Faraday::Whatever::Foo
  # @param key [Symbol] key for the registered middleware.
  # @raise [Faraday::Error] if given key is not registered
  # @return [Class] a middleware Class.
  #
  # pkg:gem/faraday#lib/faraday/middleware_registry.rb:89
  def lookup_middleware(key); end

  # pkg:gem/faraday#lib/faraday/middleware_registry.rb:94
  def middleware_mutex(&block); end

  # Register middleware class(es) on the current module.
  #
  #        }] Middleware mapping from a lookup symbol to a reference to the
  #        middleware.
  #        Classes can be expressed as:
  #          - a fully qualified constant
  #          - a Symbol
  #          - a Proc that will be lazily called to return the former
  #          - an array is given, its first element is the constant or symbol,
  #            and its second is a file to `require`.
  #
  # @example Lookup by a constant
  #
  #   module Faraday
  #   class Whatever
  #   # Middleware looked up by :foo returns Faraday::Whatever::Foo.
  #   register_middleware foo: Foo
  #   end
  #   end
  # @example Lookup by a symbol
  #
  #   module Faraday
  #   class Whatever
  #   # Middleware looked up by :bar returns
  #   # Faraday::Whatever.const_get(:Bar)
  #   register_middleware bar: :Bar
  #   end
  #   end
  # @example Lookup by a symbol and string in an array
  #
  #   module Faraday
  #   class Whatever
  #   # Middleware looked up by :baz requires 'baz' and returns
  #   # Faraday::Whatever.const_get(:Baz)
  #   register_middleware baz: [:Baz, 'baz']
  #   end
  #   end
  # @param autoload_path [String] Middleware autoload path
  # @param mapping [Hash{
  # Symbol => Module,
  # Symbol => Array<Module, Symbol, String>,] apping [Hash{
  #   Symbol => Module,
  #   Symbol => Array<Module, Symbol, String>,
  # @return [void]
  #
  # pkg:gem/faraday#lib/faraday/middleware_registry.rb:54
  def register_middleware(autoload_path = T.unsafe(nil), mapping = T.unsafe(nil)); end

  # Unregister a previously registered middleware class.
  #
  # @param key [Symbol] key for the registered middleware.
  #
  # pkg:gem/faraday#lib/faraday/middleware_registry.rb:68
  def unregister_middleware(key); end
end

# This is the default encoder for Faraday requests.
# Using this encoder, parameters will be encoded respecting their structure,
# so you can send objects such as Arrays or Hashes as parameters
# for your requests.
#
# pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:162
module Faraday::NestedParamsEncoder
  extend ::Faraday::EncodeMethods
  extend ::Faraday::DecodeMethods

  class << self
    # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:167
    def escape(*args, **_arg1, &block); end

    # Returns the value of attribute sort_params.
    #
    # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:164
    def sort_params; end

    # Sets the attribute sort_params
    #
    # @param value the value to set the attribute sort_params to.
    #
    # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:164
    def sort_params=(_arg0); end

    # pkg:gem/faraday#lib/faraday/encoders/nested_params_encoder.rb:167
    def unescape(*args, **_arg1, &block); end
  end
end

# Raised by Faraday::Response::RaiseError in case of a nil status in response.
#
# pkg:gem/faraday#lib/faraday/error.rb:116
class Faraday::NilStatusError < ::Faraday::ServerError
  # @return [NilStatusError] a new instance of NilStatusError
  #
  # pkg:gem/faraday#lib/faraday/error.rb:117
  def initialize(exc, response = T.unsafe(nil)); end
end

# Subclasses Struct with some special helpers for converting from a Hash to
# a Struct.
#
# pkg:gem/faraday#lib/faraday/options.rb:6
class Faraday::Options < ::Struct
  # pkg:gem/faraday#lib/faraday/options.rb:185
  def [](key); end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:46
  def clear; end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:71
  def deep_dup; end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:39
  def delete(key); end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:13
  def each; end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:106
  def each_key(&block); end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:120
  def each_value(&block); end

  # Public
  #
  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/options.rb:101
  def empty?; end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:76
  def fetch(key, *args); end

  # Public
  #
  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/options.rb:117
  def has_key?(key); end

  # Public
  #
  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/options.rb:131
  def has_value?(value); end

  # Internal
  #
  # pkg:gem/faraday#lib/faraday/options.rb:144
  def inspect; end

  # Public
  #
  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/options.rb:113
  def key?(key); end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:96
  def keys; end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:66
  def merge(other); end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:51
  def merge!(other); end

  # pkg:gem/faraday#lib/faraday/options.rb:194
  def symbolized_key_set; end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:134
  def to_hash; end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:22
  def update(obj); end

  # Public
  #
  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/options.rb:127
  def value?(value); end

  # Public
  #
  # pkg:gem/faraday#lib/faraday/options.rb:91
  def values_at(*keys); end

  class << self
    # Internal
    #
    # pkg:gem/faraday#lib/faraday/options.rb:166
    def attribute_options; end

    # pkg:gem/faraday#lib/faraday/options.rb:204
    def fetch_error_class; end

    # Public
    #
    # pkg:gem/faraday#lib/faraday/options.rb:8
    def from(value); end

    # @private
    #
    # pkg:gem/faraday#lib/faraday/options.rb:198
    def inherited(subclass); end

    # pkg:gem/faraday#lib/faraday/options.rb:170
    def memoized(key, &block); end

    # pkg:gem/faraday#lib/faraday/options.rb:181
    def memoized_attributes; end

    # Internal
    #
    # pkg:gem/faraday#lib/faraday/options.rb:156
    def options(mapping); end

    # Internal
    #
    # pkg:gem/faraday#lib/faraday/options.rb:161
    def options_for(key); end
  end
end

# Multipart value used to POST data with a content type.
#
# pkg:gem/faraday#lib/faraday/param_part.rb:5
class Faraday::ParamPart
  # @param content_id [String] Optional String of this value's Content-ID.
  # @param content_type [String] String content type of the value.
  # @param value [String] Uploaded content as a String.
  # @return [Faraday::ParamPart]
  #
  # pkg:gem/faraday#lib/faraday/param_part.rb:11
  def initialize(value, content_type, content_id = T.unsafe(nil)); end

  # The value's content ID, if given.
  #
  # @return [String, nil]
  #
  # pkg:gem/faraday#lib/faraday/param_part.rb:51
  def content_id; end

  # The value's content type.
  #
  # @return [String]
  #
  # pkg:gem/faraday#lib/faraday/param_part.rb:46
  def content_type; end

  # Returns a Hash of String key/value pairs.
  #
  # @return [Hash]
  #
  # pkg:gem/faraday#lib/faraday/param_part.rb:31
  def headers; end

  # Converts this value to a form part.
  #
  # @param boundary [String] String multipart boundary that must not exist in
  #   the content exactly.
  # @param key [String] String key name for this value.
  # @return [Faraday::Parts::Part]
  #
  # pkg:gem/faraday#lib/faraday/param_part.rb:24
  def to_part(boundary, key); end

  # The content to upload.
  #
  # @return [String]
  #
  # pkg:gem/faraday#lib/faraday/param_part.rb:41
  def value; end
end

# Raised by FaradayMiddleware::ResponseMiddleware
#
# pkg:gem/faraday#lib/faraday/error.rb:132
class Faraday::ParsingError < ::Faraday::Error; end

# pkg:gem/faraday#lib/faraday/file_part.rb:61
Faraday::Parts = Multipart::Post::Parts

# Raised by Faraday::Response::RaiseError in case of a 407 response.
#
# pkg:gem/faraday#lib/faraday/error.rb:93
class Faraday::ProxyAuthError < ::Faraday::ClientError; end

# ProxyOptions contains the configurable properties for the proxy
# configuration used when making an HTTP request.
#
# pkg:gem/faraday#lib/faraday/options/proxy_options.rb:6
class Faraday::ProxyOptions < ::Faraday::Options
  extend ::Forwardable

  # pkg:gem/faraday#lib/faraday/options/proxy_options.rb:8
  def host(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/options/proxy_options.rb:8
  def host=(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/options/proxy_options.rb:26
  def password; end

  # pkg:gem/faraday#lib/faraday/options/proxy_options.rb:8
  def path(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/options/proxy_options.rb:8
  def path=(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/options/proxy_options.rb:8
  def port(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/options/proxy_options.rb:8
  def port=(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/options/proxy_options.rb:8
  def scheme(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/options/proxy_options.rb:8
  def scheme=(*args, **_arg1, &block); end

  # pkg:gem/faraday#lib/faraday/options/proxy_options.rb:25
  def user; end

  class << self
    # pkg:gem/faraday#lib/faraday/options/proxy_options.rb:11
    def from(value); end
  end
end

# A Builder that processes requests into responses by passing through an inner
# middleware stack (heavily inspired by Rack).
#
# @example
#   Faraday::Connection.new(url: 'http://sushi.com') do |builder|
#   builder.request  :url_encoded  # Faraday::Request::UrlEncoded
#   builder.adapter  :net_http     # Faraday::Adapter::NetHttp
#   end
#
# pkg:gem/faraday#lib/faraday/rack_builder.rb:15
class Faraday::RackBuilder
  # @return [RackBuilder] a new instance of RackBuilder
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:61
  def initialize(handlers = T.unsafe(nil), adapter = T.unsafe(nil), &block); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:179
  def ==(other); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:80
  def [](idx); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:111
  def adapter(klass = T.unsafe(nil), *args, **_arg2, &block); end

  # The "rack app" wrapped in middleware. All requests are sent here.
  #
  # The builder is responsible for creating the app object. After this,
  # the builder gets locked to ensure no further modifications are made
  # to the middleware stack.
  #
  # Returns an object that responds to `call` and returns a Response.
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:164
  def app; end

  # @yield [_self]
  # @yieldparam _self [Faraday::RackBuilder] the object that the method was called on
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:73
  def build(options = T.unsafe(nil)); end

  # ENV Keys
  # :http_method - a symbolized request HTTP method (:get, :post)
  # :body   - the request body that will eventually be converted to a string.
  # :url    - URI instance for the current request.
  # :status           - HTTP response status code
  # :request_headers  - hash of HTTP Headers to be sent to the server
  # :response_headers - Hash of HTTP headers from the server
  # :parallel_manager - sent if the connection is in parallel mode
  # :request - Hash of options for configuring the request.
  #   :timeout      - open/read timeout Integer in seconds
  #   :open_timeout - read timeout Integer in seconds
  #   :proxy        - Hash of proxy options
  #     :uri        - Proxy Server URI
  #     :user       - Proxy server username
  #     :password   - Proxy server password
  # :ssl - Hash of options for configuring SSL requests.
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:205
  def build_env(connection, request); end

  # Processes a Request into a Response by passing it through this Builder's
  # middleware stack.
  #
  # @param connection [Faraday::Connection]
  # @param request [Faraday::Request]
  # @return [Faraday::Response]
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:153
  def build_response(connection, request); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:141
  def delete(handler); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:185
  def dup; end

  # Returns the value of attribute handlers.
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:19
  def handlers; end

  # Sets the attribute handlers
  #
  # @param value the value to set the attribute handlers to.
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:19
  def handlers=(_arg0); end

  # methods to push onto the various positions in the stack:
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:120
  def insert(index, *args, **_arg2, &block); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:129
  def insert_after(index, *args, **_arg2, &block); end

  # methods to push onto the various positions in the stack:
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:127
  def insert_before(index, *args, **_arg2, &block); end

  # Locks the middleware stack to ensure no further modifications are made.
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:85
  def lock!; end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:89
  def locked?; end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:103
  def request(key, *args, **_arg2, &block); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:107
  def response(key, *args, **_arg2, &block); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:134
  def swap(index, *args, **_arg2, &block); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:171
  def to_app; end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:93
  def use(klass, *args, **_arg2, &block); end

  private

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:230
  def adapter_set?; end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:242
  def assert_index(index); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:234
  def is_adapter?(klass); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:224
  def raise_if_adapter(klass); end

  # @raise [StackLocked]
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:220
  def raise_if_locked; end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:238
  def use_symbol(mod, key, *args, **_arg3, &block); end
end

# borrowed from ActiveSupport::Dependencies::Reference &
# ActionDispatch::MiddlewareStack::Middleware
#
# pkg:gem/faraday#lib/faraday/rack_builder.rb:26
class Faraday::RackBuilder::Handler
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:31
  def initialize(klass, *args, **_arg2, &block); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:46
  def ==(other); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:56
  def build(app = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:42
  def inspect; end

  # pkg:gem/faraday#lib/faraday/rack_builder.rb:38
  def klass; end

  # Returns the value of attribute name.
  #
  # pkg:gem/faraday#lib/faraday/rack_builder.rb:29
  def name; end
end

# pkg:gem/faraday#lib/faraday/rack_builder.rb:27
Faraday::RackBuilder::Handler::REGISTRY = T.let(T.unsafe(nil), Faraday::AdapterRegistry)

# pkg:gem/faraday#lib/faraday/rack_builder.rb:218
Faraday::RackBuilder::LOCK_ERR = T.let(T.unsafe(nil), String)

# Used to detect missing arguments
#
# pkg:gem/faraday#lib/faraday/rack_builder.rb:17
Faraday::RackBuilder::NO_ARGUMENT = T.let(T.unsafe(nil), Object)

# Error raised when trying to modify the stack after calling `lock!`
#
# pkg:gem/faraday#lib/faraday/rack_builder.rb:22
class Faraday::RackBuilder::StackLocked < ::RuntimeError; end

# Used to setup URLs, params, headers, and the request body in a sane manner.
#
#
# @example
#   @connection.post do |req|
#   req.url 'http://localhost', 'a' => '1' # 'http://localhost?a=1'
#   req.headers['b'] = '2' # Header
#   req.params['c']  = '3' # GET Param
#   req['b']         = '2' # also Header
#   req.body = 'abc'
#   end
#
# pkg:gem/faraday#lib/faraday/request.rb:31
class Faraday::Request < ::Struct
  extend ::Faraday::MiddlewareRegistry
  extend ::Faraday::AutoloadHelper

  # @param key [Object] key to look up in headers
  # @return [Object] value of the given header name
  #
  # pkg:gem/faraday#lib/faraday/request.rb:114
  def [](key); end

  # @param key [Object] key of header to write
  # @param value [Object] value of header
  #
  # pkg:gem/faraday#lib/faraday/request.rb:120
  def []=(key, value); end

  # Replace request headers, preserving the existing hash type.
  #
  # @param hash [Hash] new headers
  #
  # pkg:gem/faraday#lib/faraday/request.rb:83
  def headers=(hash); end

  # Marshal serialization support.
  #
  # @return [Hash] the hash ready to be serialized in Marshal.
  #
  # pkg:gem/faraday#lib/faraday/request.rb:127
  def marshal_dump; end

  # Marshal serialization support.
  # Restores the instance variables according to the +serialised+.
  #
  # @param serialised [Hash] the serialised object.
  #
  # pkg:gem/faraday#lib/faraday/request.rb:141
  def marshal_load(serialised); end

  # pkg:gem/faraday#lib/faraday/request.rb:61
  def method; end

  # Replace params, preserving the existing hash type.
  #
  # @param hash [Hash] new params
  #
  # pkg:gem/faraday#lib/faraday/request.rb:72
  def params=(hash); end

  # @return [Env] the Env for this Request
  #
  # pkg:gem/faraday#lib/faraday/request.rb:151
  def to_env(connection); end

  # Update path and params.
  #
  # @param params [Hash, nil]
  # @param path [URI, String]
  # @return [void]
  #
  # pkg:gem/faraday#lib/faraday/request.rb:96
  def url(path, params = T.unsafe(nil)); end

  class << self
    # @param request_method [String]
    # @return [Request]
    # @yield [request] for block customization, if block given
    # @yieldparam request [Request]
    #
    # pkg:gem/faraday#lib/faraday/request.rb:55
    def create(request_method); end
  end
end

# Request middleware for the Authorization HTTP header
#
# pkg:gem/faraday#lib/faraday/request/authorization.rb:6
class Faraday::Request::Authorization < ::Faraday::Middleware
  # @param app [#call]
  # @param token [String, Symbol, Hash] Token value for the Authorization
  # @param type [String, Symbol] Type of Authorization
  # @return [Authorization] a new instance of Authorization
  #
  # pkg:gem/faraday#lib/faraday/request/authorization.rb:43
  def initialize(app, type, token); end

  # @param env [Faraday::Env]
  #
  # pkg:gem/faraday#lib/faraday/request/authorization.rb:49
  def call(env); end

  class << self
    # @api private
    # @param hash [Hash]
    # @param type [String]
    # @return [String] type followed by comma-separated key=value pairs
    #
    # pkg:gem/faraday#lib/faraday/request/authorization.rb:31
    def build_hash(type, hash); end

    # @param token [String, Symbol, Hash]
    # @param type [String, Symbol]
    # @return [String] a header value
    #
    # pkg:gem/faraday#lib/faraday/request/authorization.rb:14
    def header(type, token); end
  end
end

# pkg:gem/faraday#lib/faraday/request/authorization.rb:8
Faraday::Request::Authorization::KEY = T.let(T.unsafe(nil), String)

# Authorization middleware for Basic Authentication.
#
# pkg:gem/faraday#lib/faraday/request/basic_authentication.rb:8
class Faraday::Request::BasicAuthentication < ::Faraday::Request::Authorization
  class << self
    # @param login [String]
    # @param pass [String]
    # @return [String] a Basic Authentication header line
    #
    # pkg:gem/faraday#lib/faraday/request/basic_authentication.rb:13
    def header(login, pass); end
  end
end

# Middleware for instrumenting Requests.
#
# pkg:gem/faraday#lib/faraday/request/instrumentation.rb:6
class Faraday::Request::Instrumentation < ::Faraday::Middleware
  # Instruments requests using Active Support.
  #
  # Measures time spent only for synchronous requests.
  #
  # @example Using ActiveSupport::Notifications to measure time spent
  #   for Faraday requests.
  #   ActiveSupport::Notifications
  #   .subscribe('request.faraday') do |name, starts, ends, _, env|
  #   url = env[:url]
  #   http_method = env[:method].to_s.upcase
  #   duration = ends - starts
  #   $stderr.puts '[%s] %s %s (%.3f s)' %
  #   [url.host, http_method, url.request_uri, duration]
  #   end
  # @option options
  # @option options
  # @param app [#call]
  # @param options [nil, Hash] Options hash
  # @return [Instrumentation] a new instance of Instrumentation
  #
  # pkg:gem/faraday#lib/faraday/request/instrumentation.rb:40
  def initialize(app, options = T.unsafe(nil)); end

  # @param env [Faraday::Env]
  #
  # pkg:gem/faraday#lib/faraday/request/instrumentation.rb:47
  def call(env); end
end

# Options class used in Request::Instrumentation class.
#
# pkg:gem/faraday#lib/faraday/request/instrumentation.rb:8
class Faraday::Request::Instrumentation::Options < ::Faraday::Options
  # @return [Class]
  #
  # pkg:gem/faraday#lib/faraday/request/instrumentation.rb:15
  def instrumenter; end

  # @return [String]
  #
  # pkg:gem/faraday#lib/faraday/request/instrumentation.rb:10
  def name; end
end

# Middleware for supporting multi-part requests.
#
# pkg:gem/faraday#lib/faraday/request/multipart.rb:9
class Faraday::Request::Multipart < ::Faraday::Request::UrlEncoded
  # @return [Multipart] a new instance of Multipart
  #
  # pkg:gem/faraday#lib/faraday/request/multipart.rb:15
  def initialize(app = T.unsafe(nil), options = T.unsafe(nil)); end

  # Checks for files in the payload, otherwise leaves everything untouched.
  #
  # @param env [Faraday::Env]
  #
  # pkg:gem/faraday#lib/faraday/request/multipart.rb:23
  def call(env); end

  # @param env [Faraday::Env]
  # @param params [Hash]
  #
  # pkg:gem/faraday#lib/faraday/request/multipart.rb:57
  def create_multipart(env, params); end

  # Returns true if obj is an enumerable with values that are multipart.
  #
  # @param obj [Object]
  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/request/multipart.rb:46
  def has_multipart?(obj); end

  # pkg:gem/faraday#lib/faraday/request/multipart.rb:69
  def part(boundary, key, value); end

  # @param params [Hash]
  # @param pieces [Array]
  # @param prefix [String]
  #
  # pkg:gem/faraday#lib/faraday/request/multipart.rb:85
  def process_params(params, prefix = T.unsafe(nil), pieces = T.unsafe(nil), &block); end

  # @param env [Faraday::Env]
  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/request/multipart.rb:34
  def process_request?(env); end

  # @return [String]
  #
  # pkg:gem/faraday#lib/faraday/request/multipart.rb:78
  def unique_boundary; end
end

# pkg:gem/faraday#lib/faraday/request/multipart.rb:12
Faraday::Request::Multipart::DEFAULT_BOUNDARY_PREFIX = T.let(T.unsafe(nil), String)

# Catches exceptions and retries each request a limited number of times.
#
# By default, it retries 2 times and handles only timeout exceptions. It can
# be configured with an arbitrary number of retries, a list of exceptions to
# handle, a retry interval, a percentage of randomness to add to the retry
# interval, and a backoff factor.
#
# This example will result in a first interval that is random between 0.05
# and 0.075 and a second interval that is random between 0.1 and 0.125.
#
# @example Configure Retry middleware using intervals
#   Faraday.new do |conn|
#   conn.request(:retry, max: 2,
#   interval: 0.05,
#   interval_randomness: 0.5,
#   backoff_factor: 2,
#   exceptions: [CustomException, 'Timeout::Error'])
#
#   conn.adapter(:net_http) # NB: Last middleware must be the adapter
#   end
#
# pkg:gem/faraday#lib/faraday/request/retry.rb:25
class Faraday::Request::Retry < ::Faraday::Middleware
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @option options
  # @param app [#call]
  # @param options [Hash]
  # @return [Retry] a new instance of Retry
  #
  # pkg:gem/faraday#lib/faraday/request/retry.rb:122
  def initialize(app, options = T.unsafe(nil)); end

  # An exception matcher for the rescue clause can usually be any object
  # that responds to `===`, but for Ruby 1.8 it has to be a Class or Module.
  #
  # @api private
  # @param exceptions [Array]
  # @return [Module] an exception matcher
  #
  # pkg:gem/faraday#lib/faraday/request/retry.rb:176
  def build_exception_matcher(exceptions); end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:128
  def calculate_sleep_amount(retries, env); end

  # @param env [Faraday::Env]
  #
  # pkg:gem/faraday#lib/faraday/request/retry.rb:142
  def call(env); end

  private

  # MDN spec for Retry-After header:
  # https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After
  #
  # pkg:gem/faraday#lib/faraday/request/retry.rb:212
  def calculate_retry_after(env); end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:227
  def calculate_retry_interval(retries); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/request/retry.rb:197
  def retry_request?(env, exception); end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:202
  def rewind_files(body); end
end

# pkg:gem/faraday#lib/faraday/request/retry.rb:26
Faraday::Request::Retry::DEFAULT_EXCEPTIONS = T.let(T.unsafe(nil), Array)

# pkg:gem/faraday#lib/faraday/request/retry.rb:30
Faraday::Request::Retry::IDEMPOTENT_METHODS = T.let(T.unsafe(nil), Array)

# Options contains the configurable parameters for the Retry middleware.
#
# pkg:gem/faraday#lib/faraday/request/retry.rb:37
class Faraday::Request::Retry::Options < ::Faraday::Options
  # pkg:gem/faraday#lib/faraday/request/retry.rb:65
  def backoff_factor; end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:69
  def exceptions; end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:53
  def interval; end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:61
  def interval_randomness; end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:49
  def max; end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:57
  def max_interval; end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:73
  def methods; end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:81
  def retry_block; end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:77
  def retry_if; end

  # pkg:gem/faraday#lib/faraday/request/retry.rb:85
  def retry_statuses; end

  class << self
    # pkg:gem/faraday#lib/faraday/request/retry.rb:41
    def from(value); end
  end
end

# pkg:gem/faraday#lib/faraday/request/retry.rb:39
Faraday::Request::Retry::Options::DEFAULT_CHECK = T.let(T.unsafe(nil), Proc)

# TokenAuthentication is a middleware that adds a 'Token' header to a
# Faraday request.
#
# pkg:gem/faraday#lib/faraday/request/token_authentication.rb:7
class Faraday::Request::TokenAuthentication < ::Faraday::Request::Authorization
  # @return [TokenAuthentication] a new instance of TokenAuthentication
  #
  # pkg:gem/faraday#lib/faraday/request/token_authentication.rb:15
  def initialize(app, token, options = T.unsafe(nil)); end

  class << self
    # Public
    #
    # pkg:gem/faraday#lib/faraday/request/token_authentication.rb:9
    def header(token, options = T.unsafe(nil)); end
  end
end

# Middleware for supporting urlencoded requests.
#
# pkg:gem/faraday#lib/faraday/request/url_encoded.rb:6
class Faraday::Request::UrlEncoded < ::Faraday::Middleware
  # Encodes as "application/x-www-form-urlencoded" if not already encoded or
  # of another type.
  #
  # @param env [Faraday::Env]
  #
  # pkg:gem/faraday#lib/faraday/request/url_encoded.rb:20
  def call(env); end

  # @param env [Faraday::Env]
  # @yield [request_body] Body of the request
  #
  # pkg:gem/faraday#lib/faraday/request/url_encoded.rb:30
  def match_content_type(env); end

  # @param env [Faraday::Env]
  # @return [Boolean] True if the request has a body and its Content-Type is
  #   urlencoded.
  #
  # pkg:gem/faraday#lib/faraday/request/url_encoded.rb:41
  def process_request?(env); end

  # @param env [Faraday::Env]
  # @return [String]
  #
  # pkg:gem/faraday#lib/faraday/request/url_encoded.rb:49
  def request_type(env); end

  class << self
    # Returns the value of attribute mime_type.
    #
    # pkg:gem/faraday#lib/faraday/request/url_encoded.rb:12
    def mime_type; end

    # Sets the attribute mime_type
    #
    # @param value the value to set the attribute mime_type to.
    #
    # pkg:gem/faraday#lib/faraday/request/url_encoded.rb:12
    def mime_type=(_arg0); end
  end
end

# pkg:gem/faraday#lib/faraday/request/url_encoded.rb:8
Faraday::Request::UrlEncoded::CONTENT_TYPE = T.let(T.unsafe(nil), String)

# RequestOptions contains the configurable properties for a Faraday request.
#
# pkg:gem/faraday#lib/faraday/options/request_options.rb:8
class Faraday::RequestOptions < ::Faraday::Options
  # pkg:gem/faraday#lib/faraday/options/request_options.rb:10
  def []=(key, value); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/options/request_options.rb:18
  def stream_response?; end
end

# Raised by Faraday::Response::RaiseError in case of a 404 response.
#
# pkg:gem/faraday#lib/faraday/error.rb:89
class Faraday::ResourceNotFound < ::Faraday::ClientError; end

# Response represents an HTTP response from making an HTTP request.
#
# pkg:gem/faraday#lib/faraday/response.rb:7
class Faraday::Response
  extend ::Forwardable
  extend ::Faraday::MiddlewareRegistry
  extend ::Faraday::AutoloadHelper

  # @return [Response] a new instance of Response
  #
  # pkg:gem/faraday#lib/faraday/response.rb:27
  def initialize(env = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/response.rb:45
  def [](*args, **_arg1, &block); end

  # Expand the env with more properties, without overriding existing ones.
  # Useful for applying request params after restoring a marshalled Response.
  #
  # pkg:gem/faraday#lib/faraday/response.rb:94
  def apply_request(request_env); end

  # pkg:gem/faraday#lib/faraday/response.rb:47
  def body; end

  # Returns the value of attribute env.
  #
  # pkg:gem/faraday#lib/faraday/response.rb:32
  def env; end

  # pkg:gem/faraday#lib/faraday/response.rb:64
  def finish(env); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/response.rb:51
  def finished?; end

  # pkg:gem/faraday#lib/faraday/response.rb:42
  def headers; end

  # because @on_complete_callbacks cannot be marshalled
  #
  # pkg:gem/faraday#lib/faraday/response.rb:84
  def marshal_dump; end

  # pkg:gem/faraday#lib/faraday/response.rb:88
  def marshal_load(env); end

  # pkg:gem/faraday#lib/faraday/response.rb:55
  def on_complete(&block); end

  # pkg:gem/faraday#lib/faraday/response.rb:38
  def reason_phrase; end

  # pkg:gem/faraday#lib/faraday/response.rb:34
  def status; end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/response.rb:72
  def success?; end

  # pkg:gem/faraday#lib/faraday/response.rb:76
  def to_hash; end
end

# Logger is a middleware that logs internal events in the HTTP request
# lifecycle to a given Logger object. By default, this logs to STDOUT. See
# Faraday::Logging::Formatter to see specifically what is logged.
#
# pkg:gem/faraday#lib/faraday/response/logger.rb:11
class Faraday::Response::Logger < ::Faraday::Response::Middleware
  # @return [Logger] a new instance of Logger
  # @yield [@formatter]
  #
  # pkg:gem/faraday#lib/faraday/response/logger.rb:12
  def initialize(app, logger = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/response/logger.rb:23
  def call(env); end

  # pkg:gem/faraday#lib/faraday/response/logger.rb:28
  def on_complete(env); end
end

# Used for simple response middleware.
#
# pkg:gem/faraday#lib/faraday/response.rb:9
class Faraday::Response::Middleware < ::Faraday::Middleware
  # Override this to modify the environment after the response has finished.
  # Calls the `parse` method if defined
  # `parse` method can be defined as private, public and protected
  #
  # pkg:gem/faraday#lib/faraday/response.rb:13
  def on_complete(env); end
end

# RaiseError is a Faraday middleware that raises exceptions on common HTTP
# client or server error responses.
#
# pkg:gem/faraday#lib/faraday/response/raise_error.rb:7
class Faraday::Response::RaiseError < ::Faraday::Response::Middleware
  # pkg:gem/faraday#lib/faraday/response/raise_error.rb:13
  def on_complete(env); end

  # pkg:gem/faraday#lib/faraday/response/raise_error.rb:40
  def response_values(env); end
end

# pkg:gem/faraday#lib/faraday/response/raise_error.rb:9
Faraday::Response::RaiseError::ClientErrorStatuses = T.let(T.unsafe(nil), Range)

# pkg:gem/faraday#lib/faraday/response/raise_error.rb:10
Faraday::Response::RaiseError::ServerErrorStatuses = T.let(T.unsafe(nil), Range)

# Exception used to control the Retry middleware.
#
# @see Faraday::Request::Retry
#
# pkg:gem/faraday#lib/faraday/error.rb:138
class Faraday::RetriableResponse < ::Faraday::Error; end

# A unified client error for SSL errors.
#
# pkg:gem/faraday#lib/faraday/error.rb:128
class Faraday::SSLError < ::Faraday::Error; end

# SSL-related options.
#
# pkg:gem/faraday#lib/faraday/options/ssl_options.rb:47
class Faraday::SSLOptions < ::Faraday::Options
  # @return [Boolean] true if should not verify
  #
  # pkg:gem/faraday#lib/faraday/options/ssl_options.rb:55
  def disable?; end

  # @return [Boolean] true if should verify
  #
  # pkg:gem/faraday#lib/faraday/options/ssl_options.rb:50
  def verify?; end
end

# Faraday server error class. Represents 5xx status responses.
#
# pkg:gem/faraday#lib/faraday/error.rb:105
class Faraday::ServerError < ::Faraday::Error; end

# A unified client error for timeouts.
#
# pkg:gem/faraday#lib/faraday/error.rb:109
class Faraday::TimeoutError < ::Faraday::ServerError
  # @return [TimeoutError] a new instance of TimeoutError
  #
  # pkg:gem/faraday#lib/faraday/error.rb:110
  def initialize(exc = T.unsafe(nil), response = T.unsafe(nil)); end
end

# Raised by Faraday::Response::RaiseError in case of a 401 response.
#
# pkg:gem/faraday#lib/faraday/error.rb:81
class Faraday::UnauthorizedError < ::Faraday::ClientError; end

# Raised by Faraday::Response::RaiseError in case of a 422 response.
#
# pkg:gem/faraday#lib/faraday/error.rb:101
class Faraday::UnprocessableEntityError < ::Faraday::ClientError; end

# Multipart value used to POST a file.
#
# @deprecated Use FilePart instead of this class. It behaves identically, with
#   a matching name to ParamPart.
#
# pkg:gem/faraday#lib/faraday/file_part.rb:59
Faraday::UploadIO = Multipart::Post::UploadIO

# Utils contains various static helper methods.
#
# pkg:gem/faraday#lib/faraday/utils/headers.rb:4
module Faraday::Utils
  private

  # Normalize URI() behavior across Ruby versions
  #
  # url - A String or URI.
  #
  # Returns a parsed URI.
  #
  # pkg:gem/faraday#lib/faraday/utils.rb:63
  def URI(url); end

  # pkg:gem/faraday#lib/faraday/utils.rb:15
  def build_nested_query(params); end

  # pkg:gem/faraday#lib/faraday/utils.rb:11
  def build_query(params); end

  # Recursive hash merge
  #
  # pkg:gem/faraday#lib/faraday/utils.rb:109
  def deep_merge(source, hash); end

  # Recursive hash update
  #
  # pkg:gem/faraday#lib/faraday/utils.rb:97
  def deep_merge!(target, hash); end

  # pkg:gem/faraday#lib/faraday/utils.rb:50
  def default_params_encoder; end

  # pkg:gem/faraday#lib/faraday/utils.rb:19
  def default_space_encoding; end

  # pkg:gem/faraday#lib/faraday/utils.rb:73
  def default_uri_parser; end

  # pkg:gem/faraday#lib/faraday/utils.rb:80
  def default_uri_parser=(parser); end

  # pkg:gem/faraday#lib/faraday/utils.rb:29
  def escape(str); end

  # Receives a String or URI and returns just
  # the path with the query string sorted.
  #
  # pkg:gem/faraday#lib/faraday/utils.rb:90
  def normalize_path(url); end

  # pkg:gem/faraday#lib/faraday/utils.rb:46
  def parse_nested_query(query); end

  # Adapted from Rack
  #
  # pkg:gem/faraday#lib/faraday/utils.rb:42
  def parse_query(query); end

  # pkg:gem/faraday#lib/faraday/utils.rb:113
  def sort_query_params(query); end

  # pkg:gem/faraday#lib/faraday/utils.rb:35
  def unescape(str); end

  class << self
    # Normalize URI() behavior across Ruby versions
    #
    # url - A String or URI.
    #
    # Returns a parsed URI.
    #
    # pkg:gem/faraday#lib/faraday/utils.rb:63
    def URI(url); end

    # pkg:gem/faraday#lib/faraday/utils.rb:15
    def build_nested_query(params); end

    # pkg:gem/faraday#lib/faraday/utils.rb:11
    def build_query(params); end

    # Recursive hash merge
    #
    # pkg:gem/faraday#lib/faraday/utils.rb:109
    def deep_merge(source, hash); end

    # Recursive hash update
    #
    # pkg:gem/faraday#lib/faraday/utils.rb:97
    def deep_merge!(target, hash); end

    # pkg:gem/faraday#lib/faraday/utils.rb:50
    def default_params_encoder; end

    # Sets the attribute default_params_encoder
    #
    # @param value the value to set the attribute default_params_encoder to.
    #
    # pkg:gem/faraday#lib/faraday/utils.rb:55
    def default_params_encoder=(_arg0); end

    # pkg:gem/faraday#lib/faraday/utils.rb:19
    def default_space_encoding; end

    # Sets the attribute default_space_encoding
    #
    # @param value the value to set the attribute default_space_encoding to.
    #
    # pkg:gem/faraday#lib/faraday/utils.rb:24
    def default_space_encoding=(_arg0); end

    # pkg:gem/faraday#lib/faraday/utils.rb:73
    def default_uri_parser; end

    # pkg:gem/faraday#lib/faraday/utils.rb:80
    def default_uri_parser=(parser); end

    # pkg:gem/faraday#lib/faraday/utils.rb:29
    def escape(str); end

    # Receives a String or URI and returns just
    # the path with the query string sorted.
    #
    # pkg:gem/faraday#lib/faraday/utils.rb:90
    def normalize_path(url); end

    # pkg:gem/faraday#lib/faraday/utils.rb:46
    def parse_nested_query(query); end

    # Adapted from Rack
    #
    # pkg:gem/faraday#lib/faraday/utils.rb:42
    def parse_query(query); end

    # pkg:gem/faraday#lib/faraday/utils.rb:113
    def sort_query_params(query); end

    # pkg:gem/faraday#lib/faraday/utils.rb:35
    def unescape(str); end
  end
end

# pkg:gem/faraday#lib/faraday/utils.rb:39
Faraday::Utils::DEFAULT_SEP = T.let(T.unsafe(nil), Regexp)

# pkg:gem/faraday#lib/faraday/utils.rb:27
Faraday::Utils::ESCAPE_RE = T.let(T.unsafe(nil), Regexp)

# A case-insensitive Hash that preserves the original case of a header
# when set.
#
# Adapted from Rack::Utils::HeaderHash
#
# pkg:gem/faraday#lib/faraday/utils/headers.rb:9
class Faraday::Utils::Headers < ::Hash
  # @return [Headers] a new instance of Headers
  #
  # pkg:gem/faraday#lib/faraday/utils/headers.rb:20
  def initialize(hash = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/utils/headers.rb:52
  def [](key); end

  # pkg:gem/faraday#lib/faraday/utils/headers.rb:57
  def []=(key, val); end

  # pkg:gem/faraday#lib/faraday/utils/headers.rb:71
  def delete(key); end

  # pkg:gem/faraday#lib/faraday/utils/headers.rb:65
  def fetch(key, *args, &block); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/utils/headers.rb:84
  def has_key?(key); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/utils/headers.rb:80
  def include?(key); end

  # pkg:gem/faraday#lib/faraday/utils/headers.rb:26
  def initialize_names; end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/utils/headers.rb:86
  def key?(key); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/utils/headers.rb:85
  def member?(key); end

  # pkg:gem/faraday#lib/faraday/utils/headers.rb:95
  def merge(other); end

  # pkg:gem/faraday#lib/faraday/utils/headers.rb:88
  def merge!(other); end

  # pkg:gem/faraday#lib/faraday/utils/headers.rb:111
  def parse(header_string); end

  # pkg:gem/faraday#lib/faraday/utils/headers.rb:100
  def replace(other); end

  # pkg:gem/faraday#lib/faraday/utils/headers.rb:107
  def to_hash; end

  # pkg:gem/faraday#lib/faraday/utils/headers.rb:93
  def update(other); end

  protected

  # Returns the value of attribute names.
  #
  # pkg:gem/faraday#lib/faraday/utils/headers.rb:129
  def names; end

  private

  # Join multiple values with a comma.
  #
  # pkg:gem/faraday#lib/faraday/utils/headers.rb:134
  def add_parsed(key, value); end

  # on dup/clone, we need to duplicate @names hash
  #
  # pkg:gem/faraday#lib/faraday/utils/headers.rb:31
  def initialize_copy(other); end

  class << self
    # pkg:gem/faraday#lib/faraday/utils/headers.rb:14
    def allocate; end

    # pkg:gem/faraday#lib/faraday/utils/headers.rb:10
    def from(value); end
  end
end

# symbol -> string mapper + cache
#
# pkg:gem/faraday#lib/faraday/utils/headers.rb:40
Faraday::Utils::Headers::KeyMap = T.let(T.unsafe(nil), Hash)

# A hash with stringified keys.
#
# pkg:gem/faraday#lib/faraday/utils/params_hash.rb:6
class Faraday::Utils::ParamsHash < ::Hash
  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:7
  def [](key); end

  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:11
  def []=(key, value); end

  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:15
  def delete(key); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:23
  def has_key?(key); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:19
  def include?(key); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:25
  def key?(key); end

  # @return [Boolean]
  #
  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:24
  def member?(key); end

  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:35
  def merge(params); end

  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:33
  def merge!(params); end

  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:44
  def merge_query(query, encoder = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:39
  def replace(other); end

  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:50
  def to_query(encoder = T.unsafe(nil)); end

  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:27
  def update(params); end

  private

  # pkg:gem/faraday#lib/faraday/utils/params_hash.rb:56
  def convert_key(key); end
end

# pkg:gem/faraday#lib/faraday/version.rb:4
Faraday::VERSION = T.let(T.unsafe(nil), String)

# pkg:gem/faraday#lib/faraday.rb:12
Timer = Timeout
