# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `narray` gem.
# Please instead update this file by running `bin/tapioca gem narray`.


# pkg:gem/narray#narray/narray_ext.rb:352
module FFTW
  private

  # pkg:gem/narray#narray/narray_ext.rb:353
  def convol(a1, a2); end

  class << self
    # pkg:gem/narray#narray/narray_ext.rb:359
    def convol(a1, a2); end
  end
end

# pkg:gem/narray#narray/narray_ext.rb:9
class NArray
  def %(_arg0); end
  def &(_arg0); end
  def *(_arg0); end
  def **(_arg0); end
  def +(_arg0); end
  def -(_arg0); end
  def -@; end
  def /(_arg0); end
  def <(_arg0); end
  def <=(_arg0); end
  def <=>(_arg0); end

  # pkg:gem/narray#narray/narray_ext.rb:48
  def ==(other); end

  def >(_arg0); end
  def >=(_arg0); end
  def [](*_arg0); end
  def []=(*_arg0); end
  def ^(_arg0); end
  def abs; end
  def accum(*_arg0); end
  def add!(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/narray#narray/narray_ext.rb:36
  def all?; end

  def and(_arg0); end
  def angle; end

  # @return [Boolean]
  #
  # pkg:gem/narray#narray/narray_ext.rb:40
  def any?; end

  def arg; end
  def ceil; end
  def clone; end
  def coerce(_arg0); end
  def collect; end
  def collect!; end

  # @return [Boolean]
  #
  # pkg:gem/narray#narray/narray_ext.rb:31
  def complex?; end

  def conj; end
  def conj!; end
  def conjugate; end
  def conjugate!; end
  def count_false; end
  def count_true; end
  def cumprod; end
  def cumprod!; end
  def cumsum; end
  def cumsum!; end

  # delete rows/columns
  #
  # pkg:gem/narray#narray/narray_ext.rb:90
  def delete_at(*args); end

  def dim; end
  def dimension; end
  def div!(_arg0); end
  def dup; end
  def each; end
  def element_size; end
  def empty?; end
  def eq(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/narray#narray/narray_ext.rb:54
  def eql?(other); end

  def fill(_arg0); end
  def fill!(_arg0); end
  def flatten; end
  def flatten!; end
  def floor; end
  def ge(_arg0); end
  def gt(_arg0); end

  # pkg:gem/narray#narray/narray_ext.rb:66
  def hash; end

  def hton; end
  def htov; end
  def im; end
  def imag; end
  def imag=(_arg0); end
  def image; end
  def indgen(*_arg0); end
  def indgen!(*_arg0); end
  def inspect; end

  # @return [Boolean]
  #
  # pkg:gem/narray#narray/narray_ext.rb:26
  def integer?; end

  def le(_arg0); end
  def length; end
  def lt(_arg0); end
  def map; end
  def map!; end
  def mask(_arg0); end
  def max(*_arg0); end

  # Statistics
  #
  # pkg:gem/narray#narray/narray_ext.rb:131
  def mean(*ranks); end

  # pkg:gem/narray#narray/narray_ext.rb:186
  def median(rank = T.unsafe(nil)); end

  def min(*_arg0); end
  def mod(_arg0); end
  def mod!(_arg0); end
  def mul!(_arg0); end
  def mul_accum(*_arg0); end
  def mul_add(*_arg0); end
  def ne(_arg0); end
  def newdim(*_arg0); end
  def newdim!(*_arg0); end
  def newdim=(*_arg0); end
  def newrank(*_arg0); end
  def newrank!(*_arg0); end
  def newrank=(*_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/narray#narray/narray_ext.rb:44
  def none?; end

  def not; end
  def ntoh; end
  def or(_arg0); end
  def original; end
  def prod(*_arg0); end
  def random(*_arg0); end
  def random!(*_arg0); end

  # Normal distributed random number;  valid for floating point types
  #
  # pkg:gem/narray#narray/narray_ext.rb:200
  def randomn; end

  # alias randomn! randomn
  #
  # pkg:gem/narray#narray/narray_ext.rb:240
  def randomn!; end

  def rank; end

  # pkg:gem/narray#narray/narray_ext.rb:75
  def rank_total(*ranks); end

  def real; end
  def recip; end
  def refer; end
  def reshape(*_arg0); end
  def reshape!(*_arg0); end

  # pkg:gem/narray#narray/narray_ext.rb:245
  def reverse(*ranks); end

  # pkg:gem/narray#narray/narray_ext.rb:156
  def rms(*ranks); end

  # pkg:gem/narray#narray/narray_ext.rb:171
  def rmsdev(*ranks); end

  # pkg:gem/narray#narray/narray_ext.rb:265
  def rot90(n_times = T.unsafe(nil)); end

  def round; end
  def sbt!(_arg0); end
  def shape; end
  def shape=(*_arg0); end
  def size; end
  def sizes; end
  def slice(*_arg0); end
  def sort(*_arg0); end
  def sort!(*_arg0); end
  def sort_index(*_arg0); end

  # pkg:gem/narray#narray/narray_ext.rb:141
  def stddev(*ranks); end

  def sum(*_arg0); end
  def swap_byte; end
  def to_a; end
  def to_binary; end
  def to_f; end
  def to_i; end
  def to_s; end
  def to_string; end
  def to_type(_arg0); end
  def to_type_as_binary(_arg0); end
  def total; end
  def transpose(*_arg0); end
  def typecode; end
  def vtoh; end
  def where; end
  def where2; end
  def xor(_arg0); end
  def |(_arg0); end
  def ~; end

  class << self
    def [](*_arg0); end
    def byte(*_arg0); end

    # pkg:gem/narray#narray/narray_ext.rb:11
    def cast(array, type = T.unsafe(nil)); end

    def complex(*_arg0); end
    def dcomplex(*_arg0); end
    def dfloat(*_arg0); end
    def div(_arg0, _arg1); end
    def float(*_arg0); end
    def int(*_arg0); end
    def lint(*_arg0); end
    def mul(_arg0, _arg1); end
    def mul_add(*_arg0); end
    def new(*_arg0); end
    def object(*_arg0); end
    def ref(_arg0); end
    def refer(_arg0); end
    def scomplex(*_arg0); end
    def sfloat(*_arg0); end
    def sint(*_arg0); end
    def srand(*_arg0); end
    def to_na(*_arg0); end
    def to_narray(*_arg0); end
  end
end

NArray::BYTE = T.let(T.unsafe(nil), Integer)
NArray::CLASS_DIMENSION = T.let(T.unsafe(nil), Integer)
NArray::COMPLEX = T.let(T.unsafe(nil), Integer)
NArray::DCOMPLEX = T.let(T.unsafe(nil), Integer)
NArray::DFLOAT = T.let(T.unsafe(nil), Integer)
NArray::ENDIAN = T.let(T.unsafe(nil), Integer)
NArray::FLOAT = T.let(T.unsafe(nil), Integer)
NArray::INT = T.let(T.unsafe(nil), Integer)
NArray::LINT = T.let(T.unsafe(nil), Integer)
NArray::NARRAY_VERSION = T.let(T.unsafe(nil), String)
NArray::NONE = T.let(T.unsafe(nil), Integer)
NArray::OBJECT = T.let(T.unsafe(nil), Integer)
NArray::ROBJ = T.let(T.unsafe(nil), Integer)
NArray::SCOMPLEX = T.let(T.unsafe(nil), Integer)
NArray::SFLOAT = T.let(T.unsafe(nil), Integer)
NArray::SINT = T.let(T.unsafe(nil), Integer)

# pkg:gem/narray#narray/narray_ext.rb:285
module NMath
  private

  def acos(_arg0); end
  def acosh(_arg0); end

  # pkg:gem/narray#narray/narray_ext.rb:326
  def acot(x); end

  # pkg:gem/narray#narray/narray_ext.rb:329
  def acoth(x); end

  # pkg:gem/narray#narray/narray_ext.rb:300
  def acsc(x); end

  # pkg:gem/narray#narray/narray_ext.rb:303
  def acsch(x); end

  # pkg:gem/narray#narray/narray_ext.rb:313
  def asec(x); end

  # pkg:gem/narray#narray/narray_ext.rb:316
  def asech(x); end

  def asin(_arg0); end
  def asinh(_arg0); end
  def atan(_arg0); end
  def atan2(_arg0, _arg1); end
  def atanh(_arg0); end
  def cos(_arg0); end
  def cosh(_arg0); end

  # pkg:gem/narray#narray/narray_ext.rb:320
  def cot(x); end

  # pkg:gem/narray#narray/narray_ext.rb:323
  def coth(x); end

  # Statistics
  #
  # pkg:gem/narray#narray/narray_ext.rb:334
  def covariance(x, y, *ranks); end

  # Trigonometric function
  #
  # pkg:gem/narray#narray/narray_ext.rb:294
  def csc(x); end

  # pkg:gem/narray#narray/narray_ext.rb:297
  def csch(x); end

  def exp(_arg0); end
  def log(_arg0); end
  def log10(_arg0); end
  def log2(_arg0); end

  # pkg:gem/narray#narray/narray_ext.rb:289
  def recip(x); end

  # pkg:gem/narray#narray/narray_ext.rb:307
  def sec(x); end

  # pkg:gem/narray#narray/narray_ext.rb:310
  def sech(x); end

  def sin(_arg0); end
  def sinh(_arg0); end
  def sqrt(_arg0); end
  def tan(_arg0); end
  def tanh(_arg0); end

  class << self
    def acos(_arg0); end
    def acosh(_arg0); end

    # pkg:gem/narray#narray/narray_ext.rb:347
    def acot(x); end

    # pkg:gem/narray#narray/narray_ext.rb:347
    def acoth(x); end

    # pkg:gem/narray#narray/narray_ext.rb:347
    def acsc(x); end

    # pkg:gem/narray#narray/narray_ext.rb:347
    def acsch(x); end

    # pkg:gem/narray#narray/narray_ext.rb:347
    def asec(x); end

    # pkg:gem/narray#narray/narray_ext.rb:347
    def asech(x); end

    def asin(_arg0); end
    def asinh(_arg0); end
    def atan(_arg0); end
    def atan2(_arg0, _arg1); end
    def atanh(_arg0); end
    def cos(_arg0); end
    def cosh(_arg0); end

    # pkg:gem/narray#narray/narray_ext.rb:346
    def cot(x); end

    # pkg:gem/narray#narray/narray_ext.rb:346
    def coth(x); end

    # Statistics
    #
    # pkg:gem/narray#narray/narray_ext.rb:348
    def covariance(x, y, *ranks); end

    # Trigonometric function
    #
    # pkg:gem/narray#narray/narray_ext.rb:346
    def csc(x); end

    # pkg:gem/narray#narray/narray_ext.rb:346
    def csch(x); end

    def exp(_arg0); end
    def log(_arg0); end
    def log10(_arg0); end
    def log2(_arg0); end

    # pkg:gem/narray#narray/narray_ext.rb:345
    def recip(x); end

    # pkg:gem/narray#narray/narray_ext.rb:346
    def sec(x); end

    # pkg:gem/narray#narray/narray_ext.rb:346
    def sech(x); end

    def sin(_arg0); end
    def sinh(_arg0); end
    def sqrt(_arg0); end
    def tan(_arg0); end
    def tanh(_arg0); end
  end
end

# pkg:gem/narray#narray/narray_ext.rb:287
NMath::E = T.let(T.unsafe(nil), Float)

# pkg:gem/narray#narray/narray_ext.rb:286
NMath::PI = T.let(T.unsafe(nil), Float)

# ------ NMatrix ------
#
# pkg:gem/narray#narray/nmatrix.rb:8
class NMatrix < ::NArray
  # pkg:gem/narray#narray/nmatrix.rb:35
  def *(other); end

  # pkg:gem/narray#narray/nmatrix.rb:80
  def **(n); end

  # @raise [TypeError]
  #
  # pkg:gem/narray#narray/nmatrix.rb:11
  def +(other); end

  # @raise [TypeError]
  #
  # pkg:gem/narray#narray/nmatrix.rb:23
  def -(other); end

  # pkg:gem/narray#narray/nmatrix.rb:59
  def /(other); end

  # pkg:gem/narray#narray/nmatrix.rb:153
  def I; end

  # @raise [TypeError]
  #
  # pkg:gem/narray#narray/nmatrix.rb:98
  def coerce_rev(other, id); end

  # pkg:gem/narray#narray/nmatrix.rb:145
  def diagonal(val); end

  # pkg:gem/narray#narray/nmatrix.rb:131
  def diagonal!(val = T.unsafe(nil)); end

  # pkg:gem/narray#narray/nmatrix.rb:152
  def identity; end

  # pkg:gem/narray#narray/nmatrix.rb:119
  def inverse; end

  def lu; end
  def lu!; end
  def lu_fact; end
  def lu_fact!; end

  # pkg:gem/narray#narray/nmatrix.rb:123
  def transpose(*arg); end

  # pkg:gem/narray#narray/nmatrix.rb:149
  def unit; end
end

# pkg:gem/narray#narray/nmatrix.rb:9
NMatrix::CLASS_DIMENSION = T.let(T.unsafe(nil), Integer)

# ------ NVector ------
#
# pkg:gem/narray#narray/nmatrix.rb:161
class NVector < ::NArray
  # pkg:gem/narray#narray/nmatrix.rb:188
  def *(other); end

  # pkg:gem/narray#narray/nmatrix.rb:226
  def **(n); end

  # @raise [TypeError]
  #
  # pkg:gem/narray#narray/nmatrix.rb:164
  def +(other); end

  # @raise [TypeError]
  #
  # pkg:gem/narray#narray/nmatrix.rb:176
  def -(other); end

  # pkg:gem/narray#narray/nmatrix.rb:207
  def /(other); end

  # @raise [TypeError]
  #
  # pkg:gem/narray#narray/nmatrix.rb:234
  def coerce_rev(other, id); end
end

# pkg:gem/narray#narray/nmatrix.rb:162
NVector::CLASS_DIMENSION = T.let(T.unsafe(nil), Integer)
