# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `open-weather-ruby-client` gem.
# Please instead update this file by running `bin/tapioca gem open-weather-ruby-client`.


# pkg:gem/open-weather-ruby-client#lib/open_weather/version.rb:3
module OpenWeather
  class << self
    # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:43
    def config; end

    # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:39
    def configure; end
  end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:4
class OpenWeather::Client
  include ::OpenWeather::Connection
  include ::OpenWeather::Request
  include ::OpenWeather::Endpoints::Current
  include ::OpenWeather::Endpoints::OneCall
  include ::OpenWeather::Endpoints::Stations

  # @return [Client] a new instance of Client
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:13
  def initialize(options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def api_key; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def api_key=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def ca_file; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def ca_file=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def ca_path; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def ca_path=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def endpoint; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def endpoint=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def lang; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def lang=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def logger; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def logger=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def open_timeout; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def open_timeout=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def proxy; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def proxy=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def timeout; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def timeout=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def units; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def units=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def user_agent; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:11
  def user_agent=(_arg0); end

  class << self
    # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:25
    def config; end

    # pkg:gem/open-weather-ruby-client#lib/open_weather/client.rb:21
    def configure; end
  end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:4
module OpenWeather::Config
  extend ::OpenWeather::Config

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def api_key; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def api_key=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def ca_file; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def ca_file=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def ca_path; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def ca_path=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def endpoint; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def endpoint=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def lang; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def lang=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def logger; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def logger=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def open_timeout; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def open_timeout=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def proxy; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def proxy=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:23
  def reset; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def timeout; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def timeout=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def units; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def units=(_arg0); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def user_agent; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:21
  def user_agent=(_arg0); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/config.rb:7
OpenWeather::Config::ATTRIBUTES = T.let(T.unsafe(nil), Array)

# pkg:gem/open-weather-ruby-client#lib/open_weather/connection.rb:4
module OpenWeather::Connection
  private

  # pkg:gem/open-weather-ruby-client#lib/open_weather/connection.rb:11
  def connection; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/connection.rb:7
  def headers; end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/current.rb:4
module OpenWeather::Endpoints; end

# pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/current.rb:5
module OpenWeather::Endpoints::Current
  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/current.rb:44
  def current_cities_geo_box(*args); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/current.rb:57
  def current_cities_geo_circle(*args); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/current.rb:69
  def current_cities_id(*args); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/current.rb:16
  def current_city(name, state = T.unsafe(nil), country = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/current.rb:21
  def current_city_id(id, options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/current.rb:11
  def current_geo(lat, lon = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/current.rb:26
  def current_weather(options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/current.rb:6
  def current_zip(code, country = T.unsafe(nil), options = T.unsafe(nil)); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/one_call.rb:5
module OpenWeather::Endpoints::OneCall
  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/one_call.rb:6
  def one_call(lat, lon = T.unsafe(nil), options = T.unsafe(nil)); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/stations.rb:5
module OpenWeather::Endpoints::Stations
  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/stations.rb:33
  def create_measurements(measurements, options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/stations.rb:26
  def delete_station(id); end

  # @raise [ArgumentError]
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/stations.rb:38
  def get_measurements(options); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/stations.rb:14
  def get_station(id); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/stations.rb:10
  def list_stations; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/stations.rb:6
  def register_station(options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/stations.rb:20
  def update_station(id, options = T.unsafe(nil)); end

  private

  # @raise [ArgumentError]
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/endpoints/stations.rb:48
  def validate_id(id); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/errors/fault.rb:4
module OpenWeather::Errors; end

# pkg:gem/open-weather-ruby-client#lib/open_weather/errors/fault.rb:5
class OpenWeather::Errors::Fault < ::Faraday::ClientError
  # pkg:gem/open-weather-ruby-client#lib/open_weather/errors/fault.rb:10
  def headers; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/errors/fault.rb:6
  def message; end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/logger.rb:6
class OpenWeather::Logger < ::Logger
  class << self
    # pkg:gem/open-weather-ruby-client#lib/open_weather/logger.rb:7
    def logger; end
  end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/temp.rb:4
module OpenWeather::Models; end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:5
module OpenWeather::Models::City; end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:6
class OpenWeather::Models::City::Weather < ::OpenWeather::Models::Model
  # @return [Weather] a new instance of Weather
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:23
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:9
  def base(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:9
  def base=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:13
  def clouds(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:13
  def clouds=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:21
  def cod(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:21
  def cod=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:7
  def coord(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:7
  def coord=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:16
  def dt(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:16
  def dt=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:18
  def id(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:18
  def id=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:10
  def main(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:10
  def main=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:20
  def name(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:20
  def name=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:14
  def rain(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:14
  def rain=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:15
  def snow(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:15
  def snow=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:17
  def sys(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:17
  def sys=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:19
  def timezone(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:19
  def timezone=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:11
  def visibility(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:11
  def visibility=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:8
  def weather(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:8
  def weather=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:12
  def wind(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/city/weather.rb:12
  def wind=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/clouds.rb:5
class OpenWeather::Models::Clouds < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/clouds.rb:6
  def all(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/clouds.rb:6
  def all=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/clouds.rb:7
  def today(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/clouds.rb:7
  def today=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/coord.rb:5
class OpenWeather::Models::Coord < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/coord.rb:7
  def Lat=(val); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/coord.rb:6
  def Lon=(val); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/coord.rb:7
  def lat(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/coord.rb:7
  def lat=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/coord.rb:6
  def lon(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/coord.rb:6
  def lon=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:5
class OpenWeather::Models::List < ::OpenWeather::Models::Model
  # @return [List] a new instance of List
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:14
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:9
  def calctime(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:9
  def calctime=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:10
  def cnt(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:10
  def cnt=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:8
  def cod(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:8
  def cod=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:10
  def count=(val); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:20
  def each(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:11
  def list(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:11
  def list=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:12
  def message(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/list.rb:12
  def message=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:5
class OpenWeather::Models::Main < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:9
  def feels_like(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:9
  def feels_like=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:9
  def feels_like_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:9
  def feels_like_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:9
  def feels_like_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:13
  def grnd_level(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:13
  def grnd_level=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:8
  def humidity(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:8
  def humidity=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:7
  def pressure(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:7
  def pressure=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:12
  def sea_level(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:12
  def sea_level=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:6
  def temp(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:6
  def temp=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:6
  def temp_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:6
  def temp_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:6
  def temp_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:11
  def temp_max(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:11
  def temp_max=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:11
  def temp_max_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:11
  def temp_max_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:11
  def temp_max_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:10
  def temp_min(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:10
  def temp_min=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:10
  def temp_min_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:10
  def temp_min_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/main.rb:10
  def temp_min_k; end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/temp.rb:5
module OpenWeather::Models::Mixins; end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/speed.rb:6
module OpenWeather::Models::Mixins::Speed
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::OpenWeather::Models::Mixins::Speed::ClassMethods

  private

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/speed.rb:25
  def to_meters_per_sec(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/speed.rb:34
  def to_miles_per_hour(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/speed.rb:9
module OpenWeather::Models::Mixins::Speed::ClassMethods
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/speed.rb:10
  def speed_property(field); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/temp.rb:6
module OpenWeather::Models::Mixins::Temp
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::OpenWeather::Models::Mixins::Temp::ClassMethods

  private

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/temp.rb:40
  def to_celcius(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/temp.rb:51
  def to_farenheit(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/temp.rb:29
  def to_kelvin(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/temp.rb:9
module OpenWeather::Models::Mixins::Temp::ClassMethods
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/mixins/temp.rb:10
  def temperature_property(field); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/model.rb:5
class OpenWeather::Models::Model < ::Hashie::Trash
  include ::Hashie::Extensions::IgnoreUndeclared
  include ::OpenWeather::Models::Mixins::Temp
  include ::OpenWeather::Models::Mixins::Speed
  extend ::OpenWeather::Models::Mixins::Temp::ClassMethods
  extend ::OpenWeather::Models::Mixins::Speed::ClassMethods

  # @return [Model] a new instance of Model
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/model.rb:12
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # Returns the value of attribute options.
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/model.rb:10
  def options; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/model.rb:18
  def units; end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:5
module OpenWeather::Models::OneCall; end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:6
class OpenWeather::Models::OneCall::CurrentWeather < ::OpenWeather::Models::Model
  # @return [CurrentWeather] a new instance of CurrentWeather
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:25
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:15
  def clouds(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:15
  def clouds=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:14
  def dew_point(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:14
  def dew_point=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:14
  def dew_point_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:14
  def dew_point_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:14
  def dew_point_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:7
  def dt(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:7
  def dt=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:11
  def feels_like(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:11
  def feels_like=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:11
  def feels_like_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:11
  def feels_like_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:11
  def feels_like_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:13
  def humidity(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:13
  def humidity=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:12
  def pressure(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:12
  def pressure=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:21
  def rain(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:21
  def rain=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:22
  def snow(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:22
  def snow=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:8
  def sunrise(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:8
  def sunrise=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:9
  def sunset(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:9
  def sunset=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:10
  def temp(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:10
  def temp=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:10
  def temp_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:10
  def temp_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:10
  def temp_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:16
  def uvi(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:16
  def uvi=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:17
  def visibility(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:17
  def visibility=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:23
  def weather(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:23
  def weather=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:20
  def wind_deg(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:20
  def wind_deg=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:19
  def wind_gust(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:19
  def wind_gust=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:19
  def wind_gust_mph; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:19
  def wind_gust_mps; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:18
  def wind_speed(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:18
  def wind_speed=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:18
  def wind_speed_mph; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/current_weather.rb:18
  def wind_speed_mps; end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:6
class OpenWeather::Models::OneCall::DailyWeather < ::OpenWeather::Models::Model
  # @return [DailyWeather] a new instance of DailyWeather
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:24
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:18
  def clouds(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:18
  def clouds=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:14
  def dew_point(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:14
  def dew_point=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:14
  def dew_point_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:14
  def dew_point_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:14
  def dew_point_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:7
  def dt(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:7
  def dt=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:11
  def feels_like(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:11
  def feels_like=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:13
  def humidity(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:13
  def humidity=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:12
  def pressure(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:12
  def pressure=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:20
  def rain(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:20
  def rain=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:21
  def snow(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:21
  def snow=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:8
  def sunrise(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:8
  def sunrise=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:9
  def sunset(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:9
  def sunset=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:10
  def temp(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:10
  def temp=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:19
  def uvi(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:19
  def uvi=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:22
  def weather(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:22
  def weather=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:17
  def wind_deg(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:17
  def wind_deg=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:16
  def wind_gust(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:16
  def wind_gust=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:16
  def wind_gust_mph; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:16
  def wind_gust_mps; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:15
  def wind_speed(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:15
  def wind_speed=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:15
  def wind_speed_mph; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/daily_weather.rb:15
  def wind_speed_mps; end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:6
class OpenWeather::Models::OneCall::FeelsLike < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:8
  def day(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:8
  def day=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:8
  def day_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:8
  def day_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:8
  def day_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:9
  def eve(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:9
  def eve=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:9
  def eve_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:9
  def eve_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:9
  def eve_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:7
  def morn(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:7
  def morn=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:7
  def morn_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:7
  def morn_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:7
  def morn_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:10
  def night(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:10
  def night=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:10
  def night_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:10
  def night_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/feels_like.rb:10
  def night_k; end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:6
class OpenWeather::Models::OneCall::HourlyWeather < ::OpenWeather::Models::Model
  # @return [HourlyWeather] a new instance of HourlyWeather
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:22
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:13
  def clouds(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:13
  def clouds=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:12
  def dew_point(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:12
  def dew_point=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:12
  def dew_point_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:12
  def dew_point_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:12
  def dew_point_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:7
  def dt(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:7
  def dt=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:9
  def feels_like(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:9
  def feels_like=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:9
  def feels_like_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:9
  def feels_like_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:9
  def feels_like_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:11
  def humidity(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:11
  def humidity=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:10
  def pressure(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:10
  def pressure=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:18
  def rain(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:18
  def rain=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:19
  def snow(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:19
  def snow=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:8
  def temp(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:8
  def temp=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:8
  def temp_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:8
  def temp_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:8
  def temp_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:14
  def visibility(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:14
  def visibility=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:20
  def weather(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:20
  def weather=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:17
  def wind_deg(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:17
  def wind_deg=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:16
  def wind_gust(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:16
  def wind_gust=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:16
  def wind_gust_mph; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:16
  def wind_gust_mps; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:15
  def wind_speed(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:15
  def wind_speed=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:15
  def wind_speed_mph; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/hourly_weather.rb:15
  def wind_speed_mps; end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/minutely_weather.rb:6
class OpenWeather::Models::OneCall::MinutelyWeather < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/minutely_weather.rb:7
  def dt(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/minutely_weather.rb:7
  def dt=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/minutely_weather.rb:8
  def precipitation(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/minutely_weather.rb:8
  def precipitation=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:6
class OpenWeather::Models::OneCall::Temp < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:8
  def day(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:8
  def day=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:8
  def day_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:8
  def day_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:8
  def day_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:9
  def eve(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:9
  def eve=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:9
  def eve_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:9
  def eve_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:9
  def eve_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:12
  def max(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:12
  def max=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:12
  def max_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:12
  def max_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:12
  def max_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:11
  def min(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:11
  def min=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:11
  def min_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:11
  def min_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:11
  def min_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:7
  def morn(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:7
  def morn=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:7
  def morn_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:7
  def morn_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:7
  def morn_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:10
  def night(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:10
  def night=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:10
  def night_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:10
  def night_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/temp.rb:10
  def night_k; end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:6
class OpenWeather::Models::OneCall::Weather < ::OpenWeather::Models::Model
  # @return [Weather] a new instance of Weather
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:15
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:10
  def current(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:10
  def current=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:13
  def daily(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:13
  def daily=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:12
  def hourly(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:12
  def hourly=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:7
  def lat(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:7
  def lat=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:8
  def lon(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:8
  def lon=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:11
  def minutely(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:11
  def minutely=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:9
  def timezone(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/one_call/weather.rb:9
  def timezone=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/rain.rb:5
class OpenWeather::Models::Rain < ::OpenWeather::Models::Model; end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/snow.rb:5
class OpenWeather::Models::Snow < ::OpenWeather::Models::Model; end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:5
class OpenWeather::Models::Station < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:6
  def ID=(val); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:11
  def altitude(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:11
  def altitude=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:12
  def created_at(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:12
  def created_at=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:30
  def delete!; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:7
  def external_id(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:7
  def external_id=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:6
  def id(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:6
  def id=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:9
  def latitude(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:9
  def latitude=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:10
  def longitude(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:10
  def longitude=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:8
  def name(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:8
  def name=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:14
  def rank(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:14
  def rank=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:16
  def register!; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:23
  def update!(attributes); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:13
  def updated_at(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/station.rb:13
  def updated_at=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:5
module OpenWeather::Models::Stations; end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/humidity.rb:6
class OpenWeather::Models::Stations::Humidity < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/humidity.rb:7
  def average(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/humidity.rb:7
  def average=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/humidity.rb:8
  def weight(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/humidity.rb:8
  def weight=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:6
class OpenWeather::Models::Stations::Measurement < ::OpenWeather::Models::Model
  # @return [Measurement] a new instance of Measurement
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:16
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:9
  def date(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:9
  def date=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:11
  def humidity(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:11
  def humidity=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:13
  def precipitation(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:13
  def precipitation=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:14
  def pressure(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:14
  def pressure=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:7
  def station_id(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:7
  def station_id=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:10
  def temp(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:10
  def temp=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:8
  def type(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:8
  def type=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:12
  def wind(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/measurement.rb:12
  def wind=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/precipitation.rb:6
class OpenWeather::Models::Stations::Precipitation < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/precipitation.rb:7
  def rain(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/precipitation.rb:7
  def rain=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/pressure.rb:6
class OpenWeather::Models::Stations::Pressure < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/pressure.rb:9
  def average(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/pressure.rb:9
  def average=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/pressure.rb:8
  def max(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/pressure.rb:8
  def max=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/pressure.rb:7
  def min(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/pressure.rb:7
  def min=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/pressure.rb:10
  def weight(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/pressure.rb:10
  def weight=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:6
class OpenWeather::Models::Stations::Temp < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:9
  def average(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:9
  def average=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:9
  def average_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:9
  def average_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:9
  def average_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:8
  def max(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:8
  def max=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:8
  def max_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:8
  def max_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:8
  def max_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:7
  def min(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:7
  def min=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:7
  def min_c; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:7
  def min_f; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:7
  def min_k; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:10
  def weight(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/stations/temp.rb:10
  def weight=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:5
class OpenWeather::Models::Sys < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:10
  def country(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:10
  def country=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:8
  def id(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:8
  def id=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:9
  def message(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:9
  def message=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:11
  def sunrise(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:11
  def sunrise=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:12
  def sunset(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:12
  def sunset=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:6
  def timezone(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:6
  def timezone=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:7
  def type(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/sys.rb:7
  def type=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/weather.rb:5
class OpenWeather::Models::Weather < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/weather.rb:8
  def description(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/weather.rb:8
  def description=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/weather.rb:10
  def icon(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/weather.rb:9
  def icon=(val); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/weather.rb:9
  def icon_uri(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/weather.rb:9
  def icon_uri=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/weather.rb:6
  def id(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/weather.rb:6
  def id=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/weather.rb:7
  def main(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/weather.rb:7
  def main=(value); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/models/wind.rb:5
class OpenWeather::Models::Wind < ::OpenWeather::Models::Model
  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/wind.rb:7
  def deg(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/wind.rb:7
  def deg=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/wind.rb:6
  def speed(&block); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/wind.rb:6
  def speed=(value); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/wind.rb:6
  def speed_mph; end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/models/wind.rb:6
  def speed_mps; end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/request.rb:4
module OpenWeather::Request
  # pkg:gem/open-weather-ruby-client#lib/open_weather/request.rb:17
  def delete(path, options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/request.rb:5
  def get(path, options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/request.rb:9
  def post(path, options = T.unsafe(nil)); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/request.rb:13
  def put(path, options = T.unsafe(nil)); end

  private

  # @param method [Symbol] - Faraday HTTP method.
  # @param options [Hash] - :appid, :lang, :units, :endpoint, :body keys will configure the request.
  #   The rest will be converted to query params for GET/DELETE, or jsonified for POST/PUT.
  # @param path [String] - URL to send.
  # @return [Object] - the Faraday::Response#body.
  #
  # pkg:gem/open-weather-ruby-client#lib/open_weather/request.rb:31
  def request(method, path, options); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/raise_error.rb:4
module OpenWeather::Response; end

# pkg:gem/open-weather-ruby-client#lib/open_weather/raise_error.rb:5
class OpenWeather::Response::RaiseError < ::Faraday::Response::Middleware
  # pkg:gem/open-weather-ruby-client#lib/open_weather/raise_error.rb:6
  def on_complete(env); end

  # pkg:gem/open-weather-ruby-client#lib/open_weather/raise_error.rb:18
  def response_values(env); end
end

# pkg:gem/open-weather-ruby-client#lib/open_weather/version.rb:4
OpenWeather::VERSION = T.let(T.unsafe(nil), String)
