# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `open-weather-ruby-client` gem.
# Please instead update this file by running `bin/tapioca gem open-weather-ruby-client`.


# source://open-weather-ruby-client//lib/open_weather/version.rb#3
module OpenWeather
  class << self
    # source://open-weather-ruby-client//lib/open_weather/config.rb#45
    def config; end

    # source://open-weather-ruby-client//lib/open_weather/config.rb#41
    def configure; end
  end
end

# source://open-weather-ruby-client//lib/open_weather/client.rb#4
class OpenWeather::Client
  include ::OpenWeather::Connection
  include ::OpenWeather::Request
  include ::OpenWeather::Endpoints::Current
  include ::OpenWeather::Endpoints::Hourly
  include ::OpenWeather::Endpoints::ThirtyDayForecast
  include ::OpenWeather::Endpoints::OneCall
  include ::OpenWeather::Endpoints::Stations

  # @return [Client] a new instance of Client
  #
  # source://open-weather-ruby-client//lib/open_weather/client.rb#15
  def initialize(options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def api_key; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def api_key=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def ca_file; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def ca_file=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def ca_path; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def ca_path=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def endpoint; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def endpoint=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def lang; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def lang=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def logger; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def logger=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def open_timeout; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def open_timeout=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def pro_endpoint; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def pro_endpoint=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def proxy; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def proxy=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def timeout; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def timeout=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def units; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def units=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def user_agent; end

  # source://open-weather-ruby-client//lib/open_weather/client.rb#13
  def user_agent=(_arg0); end

  class << self
    # source://open-weather-ruby-client//lib/open_weather/client.rb#27
    def config; end

    # source://open-weather-ruby-client//lib/open_weather/client.rb#23
    def configure; end
  end
end

# source://open-weather-ruby-client//lib/open_weather/config.rb#4
module OpenWeather::Config
  extend ::OpenWeather::Config

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def api_key; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def api_key=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def ca_file; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def ca_file=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def ca_path; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def ca_path=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def endpoint; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def endpoint=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def lang; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def lang=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def logger; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def logger=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def open_timeout; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def open_timeout=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def pro_endpoint; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def pro_endpoint=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def proxy; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def proxy=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#24
  def reset; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def timeout; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def timeout=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def units; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def units=(_arg0); end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def user_agent; end

  # source://open-weather-ruby-client//lib/open_weather/config.rb#22
  def user_agent=(_arg0); end
end

# source://open-weather-ruby-client//lib/open_weather/config.rb#7
OpenWeather::Config::ATTRIBUTES = T.let(T.unsafe(nil), Array)

# source://open-weather-ruby-client//lib/open_weather/connection.rb#4
module OpenWeather::Connection
  private

  # source://open-weather-ruby-client//lib/open_weather/connection.rb#11
  def connection; end

  # source://open-weather-ruby-client//lib/open_weather/connection.rb#7
  def headers; end
end

# source://open-weather-ruby-client//lib/open_weather/endpoints/current.rb#4
module OpenWeather::Endpoints; end

# source://open-weather-ruby-client//lib/open_weather/endpoints/current.rb#5
module OpenWeather::Endpoints::Current
  # source://open-weather-ruby-client//lib/open_weather/endpoints/current.rb#44
  def current_cities_geo_box(*args); end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/current.rb#57
  def current_cities_geo_circle(*args); end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/current.rb#69
  def current_cities_id(*args); end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/current.rb#16
  def current_city(name, state = T.unsafe(nil), country = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/current.rb#21
  def current_city_id(id, options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/current.rb#11
  def current_geo(lat, lon = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/current.rb#26
  def current_weather(options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/current.rb#6
  def current_zip(code, country = T.unsafe(nil), options = T.unsafe(nil)); end
end

# source://open-weather-ruby-client//lib/open_weather/endpoints/hourly.rb#5
module OpenWeather::Endpoints::Hourly
  # source://open-weather-ruby-client//lib/open_weather/endpoints/hourly.rb#6
  def hourly(lat, lon = T.unsafe(nil), options = T.unsafe(nil)); end
end

# source://open-weather-ruby-client//lib/open_weather/endpoints/one_call.rb#5
module OpenWeather::Endpoints::OneCall
  # source://open-weather-ruby-client//lib/open_weather/endpoints/one_call.rb#6
  def one_call(lat, lon = T.unsafe(nil), options = T.unsafe(nil)); end
end

# source://open-weather-ruby-client//lib/open_weather/endpoints/stations.rb#5
module OpenWeather::Endpoints::Stations
  # source://open-weather-ruby-client//lib/open_weather/endpoints/stations.rb#33
  def create_measurements(measurements, options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/stations.rb#26
  def delete_station(id); end

  # @raise [ArgumentError]
  #
  # source://open-weather-ruby-client//lib/open_weather/endpoints/stations.rb#38
  def get_measurements(options); end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/stations.rb#14
  def get_station(id); end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/stations.rb#10
  def list_stations; end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/stations.rb#6
  def register_station(options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/endpoints/stations.rb#20
  def update_station(id, options = T.unsafe(nil)); end

  private

  # @raise [ArgumentError]
  #
  # source://open-weather-ruby-client//lib/open_weather/endpoints/stations.rb#48
  def validate_id(id); end
end

# source://open-weather-ruby-client//lib/open_weather/endpoints/thirty_day_forecast.rb#5
module OpenWeather::Endpoints::ThirtyDayForecast
  # source://open-weather-ruby-client//lib/open_weather/endpoints/thirty_day_forecast.rb#6
  def thirty_day_forecast(lat, lon = T.unsafe(nil), options = T.unsafe(nil)); end
end

# source://open-weather-ruby-client//lib/open_weather/errors/fault.rb#4
module OpenWeather::Errors; end

# source://open-weather-ruby-client//lib/open_weather/errors/fault.rb#5
class OpenWeather::Errors::Fault < ::Faraday::ClientError
  # source://open-weather-ruby-client//lib/open_weather/errors/fault.rb#10
  def headers; end

  # source://open-weather-ruby-client//lib/open_weather/errors/fault.rb#6
  def message; end
end

# source://open-weather-ruby-client//lib/open_weather/logger.rb#6
class OpenWeather::Logger < ::Logger
  class << self
    # source://open-weather-ruby-client//lib/open_weather/logger.rb#7
    def logger; end
  end
end

# source://open-weather-ruby-client//lib/open_weather/models/mixins/temp.rb#4
module OpenWeather::Models; end

# source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#5
module OpenWeather::Models::City; end

# source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#6
class OpenWeather::Models::City::Weather < ::OpenWeather::Models::Model
  # @return [Weather] a new instance of Weather
  #
  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#23
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#9
  def base(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#9
  def base=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#13
  def clouds(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#13
  def clouds=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#21
  def cod(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#21
  def cod=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#7
  def coord(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#7
  def coord=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#16
  def dt(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#16
  def dt=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#18
  def id(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#18
  def id=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#10
  def main(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#10
  def main=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#20
  def name(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#20
  def name=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#14
  def rain(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#14
  def rain=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#15
  def snow(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#15
  def snow=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#17
  def sys(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#17
  def sys=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#19
  def timezone(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#19
  def timezone=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#11
  def visibility(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#11
  def visibility=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#8
  def weather(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#8
  def weather=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#12
  def wind(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/city/weather.rb#12
  def wind=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/clouds.rb#5
class OpenWeather::Models::Clouds < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/clouds.rb#6
  def all(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/clouds.rb#6
  def all=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/clouds.rb#7
  def today(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/clouds.rb#7
  def today=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/coord.rb#5
class OpenWeather::Models::Coord < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/coord.rb#7
  def Lat=(val); end

  # source://open-weather-ruby-client//lib/open_weather/models/coord.rb#6
  def Lon=(val); end

  # source://open-weather-ruby-client//lib/open_weather/models/coord.rb#7
  def lat(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/coord.rb#7
  def lat=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/coord.rb#6
  def lon(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/coord.rb#6
  def lon=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#5
module OpenWeather::Models::Forecast; end

# source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#6
class OpenWeather::Models::Forecast::City < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#9
  def coord(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#9
  def coord=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#10
  def country(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#10
  def country=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#7
  def id(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#7
  def id=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#8
  def name(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#8
  def name=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#14
  def population(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#14
  def population=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#12
  def sunrise(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#12
  def sunrise=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#13
  def sunset(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#13
  def sunset=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#11
  def timezone(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/city.rb#11
  def timezone=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#6
class OpenWeather::Models::Forecast::Forecast < ::OpenWeather::Models::Model
  # @return [Forecast] a new instance of Forecast
  #
  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#19
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#11
  def clouds(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#11
  def clouds=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#7
  def dt(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#7
  def dt=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#8
  def dt_txt(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#8
  def dt_txt=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#9
  def main(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#9
  def main=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#16
  def pop(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#16
  def pop=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#13
  def rain(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#13
  def rain=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#14
  def snow(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#14
  def snow=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#17
  def sys(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#17
  def sys=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#15
  def visibility(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#15
  def visibility=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#10
  def weather(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#10
  def weather=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#12
  def wind(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/forecast.rb#12
  def wind=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#6
class OpenWeather::Models::Forecast::Hourly < ::OpenWeather::Models::Model
  # @return [Hourly] a new instance of Hourly
  #
  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#16
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#10
  def calctime(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#10
  def calctime=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#14
  def city(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#14
  def city=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#11
  def cnt(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#11
  def cnt=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#9
  def cod(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#9
  def cod=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#11
  def count=(val); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#12
  def list(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#12
  def list=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#13
  def message(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/hourly.rb#13
  def message=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#6
module OpenWeather::Models::Forecast::ThirtyDay; end

# source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#7
class OpenWeather::Models::Forecast::ThirtyDay::Forecast < ::OpenWeather::Models::Model
  # @return [Forecast] a new instance of Forecast
  #
  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#22
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#18
  def clouds(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#18
  def clouds=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#17
  def deg(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#17
  def deg=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#8
  def dt(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#8
  def dt=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#12
  def feels_like(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#12
  def feels_like=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#14
  def humidity(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#14
  def humidity=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#13
  def pressure(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#13
  def pressure=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#19
  def rain(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#19
  def rain=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#20
  def snow(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#20
  def snow=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#16
  def speed(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#16
  def speed=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#9
  def sunrise(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#9
  def sunrise=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#10
  def sunset(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#10
  def sunset=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#11
  def temp(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#11
  def temp=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#15
  def weather(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/forecast.rb#15
  def weather=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#7
class OpenWeather::Models::Forecast::ThirtyDay::Temp < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#8
  def day(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#8
  def day=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#8
  def day_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#8
  def day_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#8
  def day_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#12
  def eve(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#12
  def eve=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#12
  def eve_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#12
  def eve_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#12
  def eve_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#10
  def max(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#10
  def max=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#10
  def max_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#10
  def max_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#10
  def max_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#9
  def min(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#9
  def min=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#9
  def min_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#9
  def min_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#9
  def min_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#13
  def morn(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#13
  def morn=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#13
  def morn_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#13
  def morn_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#13
  def morn_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#11
  def night(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#11
  def night=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#11
  def night_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#11
  def night_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/temp.rb#11
  def night_k; end
end

# source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#7
class OpenWeather::Models::Forecast::ThirtyDay::ThirtyDay < ::OpenWeather::Models::Model
  # @return [ThirtyDay] a new instance of ThirtyDay
  #
  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#16
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#12
  def city(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#12
  def city=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#13
  def cnt(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#13
  def cnt=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#10
  def cod(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#10
  def cod=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#14
  def list(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#14
  def list=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#11
  def message(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/forecast/thirty_day/thirty_day.rb#11
  def message=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/list.rb#5
class OpenWeather::Models::List < ::OpenWeather::Models::Model
  # @return [List] a new instance of List
  #
  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#14
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#9
  def calctime(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#9
  def calctime=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#10
  def cnt(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#10
  def cnt=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#8
  def cod(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#8
  def cod=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#10
  def count=(val); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#20
  def each(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#11
  def list(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#11
  def list=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#12
  def message(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/list.rb#12
  def message=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/main.rb#5
class OpenWeather::Models::Main < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#9
  def feels_like(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#9
  def feels_like=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#9
  def feels_like_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#9
  def feels_like_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#9
  def feels_like_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#13
  def grnd_level(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#13
  def grnd_level=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#8
  def humidity(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#8
  def humidity=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#7
  def pressure(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#7
  def pressure=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#12
  def sea_level(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#12
  def sea_level=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#6
  def temp(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#6
  def temp=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#6
  def temp_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#6
  def temp_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#6
  def temp_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#11
  def temp_max(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#11
  def temp_max=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#11
  def temp_max_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#11
  def temp_max_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#11
  def temp_max_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#10
  def temp_min(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#10
  def temp_min=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#10
  def temp_min_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#10
  def temp_min_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/main.rb#10
  def temp_min_k; end
end

# source://open-weather-ruby-client//lib/open_weather/models/mixins/temp.rb#5
module OpenWeather::Models::Mixins; end

# source://open-weather-ruby-client//lib/open_weather/models/mixins/speed.rb#6
module OpenWeather::Models::Mixins::Speed
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::OpenWeather::Models::Mixins::Speed::ClassMethods

  private

  # source://open-weather-ruby-client//lib/open_weather/models/mixins/speed.rb#25
  def to_meters_per_sec(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/mixins/speed.rb#34
  def to_miles_per_hour(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/mixins/speed.rb#9
module OpenWeather::Models::Mixins::Speed::ClassMethods
  # source://open-weather-ruby-client//lib/open_weather/models/mixins/speed.rb#10
  def speed_property(field); end
end

# source://open-weather-ruby-client//lib/open_weather/models/mixins/temp.rb#6
module OpenWeather::Models::Mixins::Temp
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::OpenWeather::Models::Mixins::Temp::ClassMethods

  private

  # source://open-weather-ruby-client//lib/open_weather/models/mixins/temp.rb#40
  def to_celcius(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/mixins/temp.rb#51
  def to_farenheit(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/mixins/temp.rb#29
  def to_kelvin(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/mixins/temp.rb#9
module OpenWeather::Models::Mixins::Temp::ClassMethods
  # source://open-weather-ruby-client//lib/open_weather/models/mixins/temp.rb#10
  def temperature_property(field); end
end

# source://open-weather-ruby-client//lib/open_weather/models/model.rb#5
class OpenWeather::Models::Model < ::Hashie::Trash
  include ::Hashie::Extensions::IgnoreUndeclared
  include ::OpenWeather::Models::Mixins::Temp
  include ::OpenWeather::Models::Mixins::Speed
  extend ::OpenWeather::Models::Mixins::Temp::ClassMethods
  extend ::OpenWeather::Models::Mixins::Speed::ClassMethods

  # @return [Model] a new instance of Model
  #
  # source://open-weather-ruby-client//lib/open_weather/models/model.rb#12
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # Returns the value of attribute options.
  #
  # source://open-weather-ruby-client//lib/open_weather/models/model.rb#10
  def options; end

  # source://open-weather-ruby-client//lib/open_weather/models/model.rb#18
  def units; end
end

# source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#5
module OpenWeather::Models::OneCall; end

# source://open-weather-ruby-client//lib/open_weather/models/one_call/alert.rb#6
class OpenWeather::Models::OneCall::Alert < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/one_call/alert.rb#11
  def description(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/alert.rb#11
  def description=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/alert.rb#10
  def end(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/alert.rb#10
  def end=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/alert.rb#8
  def event(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/alert.rb#8
  def event=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/alert.rb#7
  def sender_name(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/alert.rb#7
  def sender_name=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/alert.rb#9
  def start(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/alert.rb#9
  def start=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#6
class OpenWeather::Models::OneCall::CurrentWeather < ::OpenWeather::Models::Model
  # @return [CurrentWeather] a new instance of CurrentWeather
  #
  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#27
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#17
  def clouds(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#17
  def clouds=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#16
  def dew_point(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#16
  def dew_point=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#16
  def dew_point_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#16
  def dew_point_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#16
  def dew_point_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#7
  def dt(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#7
  def dt=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#11
  def feels_like(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#11
  def feels_like=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#11
  def feels_like_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#11
  def feels_like_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#11
  def feels_like_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#13
  def humidity(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#13
  def humidity=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#12
  def pressure(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#12
  def pressure=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#23
  def rain(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#23
  def rain=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#24
  def snow(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#24
  def snow=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#8
  def sunrise(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#8
  def sunrise=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#9
  def sunset(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#9
  def sunset=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#10
  def temp(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#10
  def temp=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#10
  def temp_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#10
  def temp_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#10
  def temp_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#18
  def uvi(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#18
  def uvi=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#19
  def visibility(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#19
  def visibility=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#25
  def weather(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#25
  def weather=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#22
  def wind_deg(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#22
  def wind_deg=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#21
  def wind_gust(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#21
  def wind_gust=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#21
  def wind_gust_mph; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#21
  def wind_gust_mps; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#20
  def wind_speed(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#20
  def wind_speed=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#20
  def wind_speed_mph; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/current_weather.rb#20
  def wind_speed_mps; end
end

# source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#6
class OpenWeather::Models::OneCall::DailyWeather < ::OpenWeather::Models::Model
  # @return [DailyWeather] a new instance of DailyWeather
  #
  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#27
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#20
  def clouds(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#20
  def clouds=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#16
  def dew_point(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#16
  def dew_point=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#16
  def dew_point_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#16
  def dew_point_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#16
  def dew_point_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#7
  def dt(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#7
  def dt=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#11
  def feels_like(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#11
  def feels_like=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#13
  def humidity(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#13
  def humidity=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#12
  def pressure(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#12
  def pressure=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#22
  def rain(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#22
  def rain=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#23
  def snow(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#23
  def snow=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#25
  def summary(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#25
  def summary=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#8
  def sunrise(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#8
  def sunrise=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#9
  def sunset(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#9
  def sunset=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#10
  def temp(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#10
  def temp=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#21
  def uvi(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#21
  def uvi=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#24
  def weather(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#24
  def weather=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#19
  def wind_deg(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#19
  def wind_deg=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#18
  def wind_gust(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#18
  def wind_gust=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#18
  def wind_gust_mph; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#18
  def wind_gust_mps; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#17
  def wind_speed(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#17
  def wind_speed=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#17
  def wind_speed_mph; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/daily_weather.rb#17
  def wind_speed_mps; end
end

# source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#6
class OpenWeather::Models::OneCall::FeelsLike < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#8
  def day(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#8
  def day=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#8
  def day_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#8
  def day_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#8
  def day_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#9
  def eve(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#9
  def eve=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#9
  def eve_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#9
  def eve_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#9
  def eve_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#7
  def morn(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#7
  def morn=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#7
  def morn_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#7
  def morn_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#7
  def morn_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#10
  def night(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#10
  def night=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#10
  def night_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#10
  def night_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/feels_like.rb#10
  def night_k; end
end

# source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#6
class OpenWeather::Models::OneCall::HourlyWeather < ::OpenWeather::Models::Model
  # @return [HourlyWeather] a new instance of HourlyWeather
  #
  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#24
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#15
  def clouds(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#15
  def clouds=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#14
  def dew_point(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#14
  def dew_point=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#14
  def dew_point_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#14
  def dew_point_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#14
  def dew_point_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#7
  def dt(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#7
  def dt=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#9
  def feels_like(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#9
  def feels_like=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#9
  def feels_like_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#9
  def feels_like_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#9
  def feels_like_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#11
  def humidity(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#11
  def humidity=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#10
  def pressure(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#10
  def pressure=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#20
  def rain(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#20
  def rain=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#21
  def snow(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#21
  def snow=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#8
  def temp(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#8
  def temp=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#8
  def temp_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#8
  def temp_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#8
  def temp_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#16
  def visibility(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#16
  def visibility=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#22
  def weather(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#22
  def weather=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#19
  def wind_deg(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#19
  def wind_deg=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#18
  def wind_gust(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#18
  def wind_gust=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#18
  def wind_gust_mph; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#18
  def wind_gust_mps; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#17
  def wind_speed(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#17
  def wind_speed=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#17
  def wind_speed_mph; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/hourly_weather.rb#17
  def wind_speed_mps; end
end

# source://open-weather-ruby-client//lib/open_weather/models/one_call/minutely_weather.rb#6
class OpenWeather::Models::OneCall::MinutelyWeather < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/one_call/minutely_weather.rb#7
  def dt(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/minutely_weather.rb#7
  def dt=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/minutely_weather.rb#8
  def precipitation(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/minutely_weather.rb#8
  def precipitation=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#6
class OpenWeather::Models::OneCall::Temp < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#8
  def day(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#8
  def day=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#8
  def day_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#8
  def day_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#8
  def day_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#9
  def eve(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#9
  def eve=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#9
  def eve_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#9
  def eve_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#9
  def eve_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#12
  def max(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#12
  def max=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#12
  def max_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#12
  def max_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#12
  def max_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#11
  def min(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#11
  def min=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#11
  def min_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#11
  def min_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#11
  def min_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#7
  def morn(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#7
  def morn=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#7
  def morn_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#7
  def morn_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#7
  def morn_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#10
  def night(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#10
  def night=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#10
  def night_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#10
  def night_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/temp.rb#10
  def night_k; end
end

# source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#6
class OpenWeather::Models::OneCall::Weather < ::OpenWeather::Models::Model
  # @return [Weather] a new instance of Weather
  #
  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#17
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#14
  def alerts(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#14
  def alerts=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#10
  def current(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#10
  def current=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#13
  def daily(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#13
  def daily=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#15
  def data(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#15
  def data=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#12
  def hourly(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#12
  def hourly=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#7
  def lat(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#7
  def lat=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#8
  def lon(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#8
  def lon=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#11
  def minutely(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#11
  def minutely=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#9
  def timezone(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/one_call/weather.rb#9
  def timezone=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/rain.rb#5
class OpenWeather::Models::Rain < ::OpenWeather::Models::Model; end

# source://open-weather-ruby-client//lib/open_weather/models/snow.rb#5
class OpenWeather::Models::Snow < ::OpenWeather::Models::Model; end

# source://open-weather-ruby-client//lib/open_weather/models/station.rb#5
class OpenWeather::Models::Station < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#6
  def ID=(val); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#11
  def altitude(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#11
  def altitude=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#12
  def created_at(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#12
  def created_at=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#30
  def delete!; end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#7
  def external_id(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#7
  def external_id=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#6
  def id(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#6
  def id=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#9
  def latitude(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#9
  def latitude=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#10
  def longitude(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#10
  def longitude=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#8
  def name(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#8
  def name=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#14
  def rank(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#14
  def rank=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#16
  def register!; end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#23
  def update!(attributes); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#13
  def updated_at(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/station.rb#13
  def updated_at=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#5
module OpenWeather::Models::Stations; end

# source://open-weather-ruby-client//lib/open_weather/models/stations/humidity.rb#6
class OpenWeather::Models::Stations::Humidity < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/stations/humidity.rb#7
  def average(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/humidity.rb#7
  def average=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/humidity.rb#8
  def weight(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/humidity.rb#8
  def weight=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#6
class OpenWeather::Models::Stations::Measurement < ::OpenWeather::Models::Model
  # @return [Measurement] a new instance of Measurement
  #
  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#16
  def initialize(args = T.unsafe(nil), options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#9
  def date(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#9
  def date=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#11
  def humidity(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#11
  def humidity=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#13
  def precipitation(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#13
  def precipitation=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#14
  def pressure(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#14
  def pressure=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#7
  def station_id(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#7
  def station_id=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#10
  def temp(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#10
  def temp=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#8
  def type(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#8
  def type=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#12
  def wind(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/measurement.rb#12
  def wind=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/stations/precipitation.rb#6
class OpenWeather::Models::Stations::Precipitation < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/stations/precipitation.rb#7
  def rain(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/precipitation.rb#7
  def rain=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/stations/pressure.rb#6
class OpenWeather::Models::Stations::Pressure < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/stations/pressure.rb#9
  def average(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/pressure.rb#9
  def average=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/pressure.rb#8
  def max(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/pressure.rb#8
  def max=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/pressure.rb#7
  def min(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/pressure.rb#7
  def min=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/pressure.rb#10
  def weight(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/pressure.rb#10
  def weight=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#6
class OpenWeather::Models::Stations::Temp < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#9
  def average(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#9
  def average=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#9
  def average_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#9
  def average_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#9
  def average_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#8
  def max(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#8
  def max=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#8
  def max_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#8
  def max_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#8
  def max_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#7
  def min(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#7
  def min=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#7
  def min_c; end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#7
  def min_f; end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#7
  def min_k; end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#10
  def weight(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/stations/temp.rb#10
  def weight=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/sys.rb#5
class OpenWeather::Models::Sys < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#10
  def country(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#10
  def country=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#8
  def id(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#8
  def id=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#9
  def message(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#9
  def message=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#11
  def sunrise(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#11
  def sunrise=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#12
  def sunset(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#12
  def sunset=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#6
  def timezone(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#6
  def timezone=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#7
  def type(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/sys.rb#7
  def type=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/weather.rb#5
class OpenWeather::Models::Weather < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/weather.rb#8
  def description(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/weather.rb#8
  def description=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/weather.rb#10
  def icon(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/weather.rb#9
  def icon=(val); end

  # source://open-weather-ruby-client//lib/open_weather/models/weather.rb#9
  def icon_uri(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/weather.rb#9
  def icon_uri=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/weather.rb#6
  def id(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/weather.rb#6
  def id=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/weather.rb#7
  def main(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/weather.rb#7
  def main=(value); end
end

# source://open-weather-ruby-client//lib/open_weather/models/wind.rb#5
class OpenWeather::Models::Wind < ::OpenWeather::Models::Model
  # source://open-weather-ruby-client//lib/open_weather/models/wind.rb#7
  def deg(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/wind.rb#7
  def deg=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/wind.rb#6
  def speed(&block); end

  # source://open-weather-ruby-client//lib/open_weather/models/wind.rb#6
  def speed=(value); end

  # source://open-weather-ruby-client//lib/open_weather/models/wind.rb#6
  def speed_mph; end

  # source://open-weather-ruby-client//lib/open_weather/models/wind.rb#6
  def speed_mps; end
end

# source://open-weather-ruby-client//lib/open_weather/request.rb#4
module OpenWeather::Request
  # source://open-weather-ruby-client//lib/open_weather/request.rb#17
  def delete(path, options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/request.rb#5
  def get(path, options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/request.rb#9
  def post(path, options = T.unsafe(nil)); end

  # source://open-weather-ruby-client//lib/open_weather/request.rb#13
  def put(path, options = T.unsafe(nil)); end

  private

  # @param method [Symbol] - Faraday HTTP method.
  # @param options [Hash] - :appid, :lang, :units, :endpoint, :body keys will configure the request.
  #   The rest will be converted to query params for GET/DELETE, or jsonified for POST/PUT.
  # @param path [String] - URL to send.
  # @return [Object] - the Faraday::Response#body.
  #
  # source://open-weather-ruby-client//lib/open_weather/request.rb#31
  def request(method, path, options); end
end

# source://open-weather-ruby-client//lib/open_weather/raise_error.rb#4
module OpenWeather::Response; end

# source://open-weather-ruby-client//lib/open_weather/raise_error.rb#5
class OpenWeather::Response::RaiseError < ::Faraday::Response::RaiseError
  # source://open-weather-ruby-client//lib/open_weather/raise_error.rb#6
  def on_complete(env); end

  # source://open-weather-ruby-client//lib/open_weather/raise_error.rb#18
  def response_values(env); end
end

# source://open-weather-ruby-client//lib/open_weather/version.rb#4
OpenWeather::VERSION = T.let(T.unsafe(nil), String)
