# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rgeo-proj4` gem.
# Please instead update this file by running `bin/tapioca gem rgeo-proj4`.


# -----------------------------------------------------------------------------
#
# Proj4 wrapper for RGeo
#
# -----------------------------------------------------------------------------
#
# source://rgeo-proj4//lib/rgeo/proj4/version.rb#3
module RGeo; end

# source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#5
module RGeo::CoordSys; end

# Store of all the created CRSToCRS
#
# source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#113
class RGeo::CoordSys::CRSStore
  include ::Singleton
  extend ::Singleton::SingletonClassMethods

  # @return [CRSStore] a new instance of CRSStore
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#123
  def initialize; end

  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#128
  def get(from, to); end

  class << self
    # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#116
    def get(from, to); end

    private

    # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#114
    def allocate; end

    # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#114
    def new(*_arg0); end
  end
end

# source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#121
class RGeo::CoordSys::CRSStore::Key < ::Struct
  # Returns the value of attribute from
  #
  # @return [Object] the current value of from
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#121
  def from; end

  # Sets the attribute from
  #
  # @param value [Object] the value to set the attribute from to.
  # @return [Object] the newly set value
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#121
  def from=(_); end

  # Returns the value of attribute to
  #
  # @return [Object] the current value of to
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#121
  def to; end

  # Sets the attribute to
  #
  # @param value [Object] the value to set the attribute to to.
  # @return [Object] the newly set value
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#121
  def to=(_); end

  class << self
    # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#121
    def [](*_arg0); end

    # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#121
    def inspect; end

    # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#121
    def keyword_init?; end

    # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#121
    def members; end

    # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#121
    def new(*_arg0); end
  end
end

# This is a Ruby wrapper around a proj crs_to_crs
# A crs_to_crs transformation object is a pipeline between two known coordinate reference systems.
# https://proj.org/development/reference/functions.html#c.proj_create_crs_to_crs
#
# It also inherits from the RGeo::CoordSys::CoordinateTransform abstract class.
#
# source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#11
class RGeo::CoordSys::CRSToCRS < ::RGeo::CoordSys::CS::CoordinateTransform
  def _area_of_use; end
  def _as_text; end
  def _identity?(_arg0, _arg1); end
  def _proj_type; end
  def _transform_coords(_arg0, _arg1, _arg2); end

  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#36
  def area_of_use; end

  # Returns the value of attribute source_cs.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#23
  def from; end

  # @return [Boolean]
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#40
  def identity?; end

  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#107
  def inspect; end

  # Returns the value of attribute source_cs.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#12
  def source_cs; end

  # Sets the attribute source_cs
  #
  # @param value the value to set the attribute source_cs to.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#12
  def source_cs=(_arg0); end

  # Returns the value of attribute target_cs.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#12
  def target_cs; end

  # Sets the attribute target_cs
  #
  # @param value the value to set the attribute target_cs to.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#12
  def target_cs=(_arg0); end

  # Returns the value of attribute target_cs.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#24
  def to; end

  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#25
  def to_wkt; end

  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#58
  def transform(from_geometry, to_factory); end

  # transform the coordinates from the initial CRS to the destination CRS
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#45
  def transform_coords(x, y, z); end

  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#97
  def transform_linear_ring(from_ring_, to_factory_); end

  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#81
  def transform_point(from_point, to_factory); end

  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#101
  def transform_polygon(from_polygon_, to_factory_); end

  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#32
  def transform_type; end

  # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#27
  def wkt_typename; end

  private

  def _create(_arg0, _arg1); end

  class << self
    def _create(_arg0, _arg1); end

    # source://rgeo-proj4//lib/rgeo/coord_sys/crs_to_crs.rb#15
    def create(from, to); end
  end
end

# PROJ uses enums for types, some methods require us to return
# the name of the type. We will use this as a lookup.
#
# source://rgeo-proj4//lib/rgeo/proj4.rb#14
RGeo::CoordSys::PROJ_TYPES = T.let(T.unsafe(nil), Array)

# This is a Ruby wrapper around a Proj4 coordinate system.
# It represents a single geographic coordinate system, which may be
# a flat projection, a geocentric (3-dimensional) coordinate system,
# or a geographic (latitude-longitude) coordinate system.
#
# Generally, these are used to define the projection for a
# Feature::Factory. You can then convert between coordinate systems
# by casting geometries between such factories using the :project
# option. You may also use this object directly to perform low-level
# coordinate transformations.
#
# source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#22
class RGeo::CoordSys::Proj4 < ::RGeo::CoordSys::CS::CoordinateSystem
  # Returns true if this Proj4 is equivalent to the given Proj4.
  #
  # Note: this tests for equivalence by comparing only the hash
  # definitions of the Proj4 objects, and returning true if those
  # definitions are equivalent. In some cases, this may still return
  # false even if the actual coordinate systems are identical, since
  # there are sometimes multiple ways to express a given coordinate
  # system.
  #
  # @return [Boolean]
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#49
  def ==(other); end

  def _as_text; end
  def _auth_name; end
  def _axis_and_unit_info(_arg0); end
  def _axis_count; end
  def _canonical_str; end
  def _crs?; end
  def _geocentric?; end
  def _geographic?; end
  def _get_geographic; end
  def _original_str; end
  def _projected?; end
  def _radians?; end
  def _set_value(_arg0, _arg1); end
  def _valid?; end

  # Returns the WKT representation of the CRS.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#112
  def as_text; end

  # Returns the string representing the authority and code of the
  # CRS if it exists, nil otherwise.
  #
  # Ex. EPSG:4326
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#122
  def auth_name; end

  # Sometimes used to assign SRIDs in factory creation
  # Also in the base CS::Info class that CS::CoordinateSystem
  # inherits from
  #
  # @return [Integer|NilClass] authority code if available
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#186
  def authority_code; end

  # Returns the "canonical" hash definition for this coordinate
  # system, as reported by Proj4. This may be slightly different
  # from the definition used to construct this object.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#92
  def canonical_hash; end

  # Returns the "canonical" string definition for this coordinate
  # system, as reported by Proj4. This may be slightly different
  # from the definition used to construct this object.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#80
  def canonical_str; end

  # Returns true if this Proj4 object represents a CRS.
  #
  # @return [Boolean]
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#177
  def crs?; end

  # Returns the value of attribute dimension.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#23
  def dimension; end

  # Sets the attribute dimension
  #
  # @param value the value to set the attribute dimension to.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#23
  def dimension=(_arg0); end

  # Psych support
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#63
  def encode_with(coder_); end

  # Returns true if this Proj4 is equivalent to the given Proj4.
  #
  # Note: this tests for equivalence by comparing only the hash
  # definitions of the Proj4 objects, and returning true if those
  # definitions are equivalent. In some cases, this may still return
  # false even if the actual coordinate systems are identical, since
  # there are sometimes multiple ways to express a given coordinate
  # system.
  #
  # @return [Boolean]
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#46
  def eql?(other); end

  # Returns true if this Proj4 object is a geocentric (3dz)
  # coordinate system.
  #
  # @return [Boolean]
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#148
  def geocentric?; end

  # Returns true if this Proj4 object is a geographic (lat-long)
  # coordinate system.
  #
  # @return [Boolean]
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#141
  def geographic?; end

  # Get the geographic (unprojected lat-long) coordinate system
  # corresponding to this coordinate system; i.e. the one that uses
  # the same ellipsoid and datum.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#173
  def geographic_coordinate_system; end

  # Gets axis details for dimension within coordinate system. Each
  # dimension in the coordinate system has a corresponding axis.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#128
  def get_axis(dimension); end

  # Get the geographic (unprojected lat-long) coordinate system
  # corresponding to this coordinate system; i.e. the one that uses
  # the same ellipsoid and datum.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#170
  def get_geographic; end

  # Gets units for dimension within coordinate system. Each
  # dimension in the coordinate system has corresponding units.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#134
  def get_units(dimension); end

  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#33
  def hash; end

  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#68
  def init_with(coder_); end

  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#25
  def inspect; end

  # Marshal support
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#53
  def marshal_dump; end

  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#57
  def marshal_load(data_); end

  # Returns the string definition originally used to construct this
  # object. Returns nil if this object wasn't created by a string
  # definition; i.e. if it was created using get_geographic.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#106
  def original_str; end

  # Returns true if this Proj4 object is a projected
  # coordinate system
  #
  # @return [Boolean]
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#155
  def projected?; end

  # Returns true if this Proj4 object uses radians rather than degrees
  # if it is a geographic coordinate system.
  #
  # @return [Boolean]
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#162
  def radians?; end

  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#29
  def to_s; end

  # Returns the WKT representation of the CRS.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#115
  def to_wkt; end

  # Low-level geometry transform method.
  # Transforms the given geometry between the given two projections.
  # The resulting geometry is constructed using the to_factory.
  # Any projections associated with the factories themselves are
  # ignored.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#203
  def transform(from_geometry, to_proj, to_factory); end

  # Low-level coordinate transform method.
  # Transforms the given coordinate (x, y, [z]) from one proj4
  # coordinate system to another. Returns an array with either two
  # or three elements.
  #
  # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#194
  def transform_coords(to_proj, x, y, z = T.unsafe(nil)); end

  private

  def _create(_arg0, _arg1); end
  def _proj_version; end
  def initialize_copy(_arg0); end

  class << self
    def _create(_arg0, _arg1); end
    def _proj_version; end

    # Create a new Proj4 object, given a definition, which may be
    # either a string, hash, or integer. If an integer is given, it
    # assumes that you are using the EPSG SRID that matches that code.
    # Returns nil if the given definition is invalid or Proj4 is not supported.
    #
    # Recognized options include:
    #
    # [<tt>:radians</tt>]
    #   If set to true, then this proj4 will represent geographic
    #   (latitude/longitude) coordinates in radians rather than
    #   degrees. If this is a geographic coordinate system, then its
    #   units will be in radians. If this is a projected coordinate
    #   system, then its units will be unchanged, but any geographic
    #   coordinate system obtained using get_geographic will use
    #   radians as its units. If this is a geocentric or other type of
    #   coordinate system, this has no effect. Default is false.
    #   (That is all coordinates are in degrees by default.)
    #
    # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#240
    def create(defn_, opts_ = T.unsafe(nil)); end

    # Create a new Proj4 object, given a definition, which may be
    # either a string, hash, or integer. If an integer is given, it
    # assumes that you are using the EPSG SRID that matches that code.
    # Returns nil if the given definition is invalid or Proj4 is not supported.
    #
    # Recognized options include:
    #
    # [<tt>:radians</tt>]
    #   If set to true, then this proj4 will represent geographic
    #   (latitude/longitude) coordinates in radians rather than
    #   degrees. If this is a geographic coordinate system, then its
    #   units will be in radians. If this is a projected coordinate
    #   system, then its units will be unchanged, but any geographic
    #   coordinate system obtained using get_geographic will use
    #   radians as its units. If this is a geocentric or other type of
    #   coordinate system, this has no effect. Default is false.
    #   (That is all coordinates are in degrees by default.)
    #
    # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#256
    def create_from_wkt(defn_, opts_ = T.unsafe(nil)); end

    # Create a new Proj4 object, given a definition, which may be
    # either a string or a hash. Raises Error::UnsupportedOperation
    # if the given definition is invalid or Proj4 is not supported.
    #
    # Recognized options include:
    #
    # [<tt>:radians</tt>]
    #   If set to true, then this proj4 will represent geographic
    #   (latitude/longitude) coordinates in radians rather than
    #   degrees. If this is a geographic coordinate system, then its
    #   units will be in radians. If this is a projected coordinate
    #   system, then its units will be unchanged, but any geographic
    #   coordinate system obtained using get_geographic will use
    #   radians as its units. If this is a geocentric or other type of
    #   coordinate system, this has no effect. Default is false.
    #   (That is all coordinates are in degrees by default.)
    #
    # @raise [Error::UnsupportedOperation]
    #
    # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#275
    def new(defn_, opts_ = T.unsafe(nil)); end

    # Returns true if Proj4 is supported in this installation.
    # If this returns false, the other methods such as create
    # will not work.
    #
    # @return [Boolean]
    #
    # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#212
    def supported?; end

    # Low-level geometry transform method.
    # Transforms the given geometry between the given two projections.
    # The resulting geometry is constructed using the to_factory.
    # Any projections associated with the factories themselves are
    # ignored.
    #
    # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#295
    def transform(from_proj, from_geometry, to_proj, to_factory); end

    # Low-level coordinate transform method.
    # Transforms the given coordinate (x, y, [z]) from one proj4
    # coordinate system to another. Returns an array with either two
    # or three elements.
    #
    # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#285
    def transform_coords(from_proj, to_proj, x, y, z = T.unsafe(nil)); end

    # Returns the Proj library version as an integer (example: 493).
    # TODO: return as string of the format "x.y.z".
    #
    # source://rgeo-proj4//lib/rgeo/coord_sys/proj4.rb#218
    def version; end
  end
end

# All RGeo errors are members of this namespace.
#
# source://rgeo-proj4//lib/rgeo/errors.rb#6
module RGeo::Error; end

# RGeo error specific to the PROJ library
#
# source://rgeo-proj4//lib/rgeo/errors.rb#12
class RGeo::Error::InvalidProjection < ::RGeo::Error::RGeoError; end

# Base class for all RGeo-related exceptions
#
# source://rgeo-proj4//lib/rgeo/errors.rb#8
class RGeo::Error::RGeoError < ::RuntimeError; end

# source://rgeo-proj4//lib/rgeo/proj4/version.rb#4
module RGeo::Proj4; end

# source://rgeo-proj4//lib/rgeo/proj4/version.rb#5
RGeo::Proj4::VERSION = T.let(T.unsafe(nil), String)
