# fix: true               # default: false
parallel: true          # default: false
format: progress        # default: Standard::Formatter
ruby_version: 3.0       # default: RUBY_VERSION
# default_ignores: false  # default: true

plugins:
  - standard-rails

standard-rails:
  target_rails_version: 7.0

# ignore:                 # default: []
  # - 'vendor/**/*'
# extend_config:          # default: []
#   - .standard_ext.yml
