# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::CI; end
module ::RequireHooks::LoadIseq; end
module ::RubyParser; end
module ::Tapioca::SourceURI; end
module RSpec::Matchers; end
