name: "Just flight CI"

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
  RUBY_VERSION: 3.3.6
  RAILS_ENV: test
  BUNDLE_PATH: vendor/bundle

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: chairmansmap_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: rails
      PGPASSWORD: password
    steps:
      - name: Install dependency libs
        run: |
          sudo apt-get update
          sudo apt-get install -y libgeos-dev libgeos-c1v5 libproj-dev proj-bin
      - name: Add GEOS to library path
        run: |
          echo "/usr/lib/x86_64-linux-gnu" | sudo tee /etc/ld.so.conf.d/geos.conf
          sudo ldconfig
      - name: Debug GEOS config
        run: |
          geos-config --version
          ls -l /usr/lib/x86_64-linux-gnu/libgeos_c.so*
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: false
      - name: Install gems
        run: bundle install
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Precompile assets
        run: bundle exec rails assets:precompile
      - name: Goofy ahh tests
        run: SIMPLECOV=true bundle exec rspec

  bundler_auditor_cheeker_breeker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Bundler auditor cheeker breeker
        run: bundle exec bundler-audit --update

  mr_brakeman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Mr. Brakeman
        run: bundle exec brakeman -q -w2

  standard_english_mate_innit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Standard english mate, innit?
        run: bundle exec standardrb

  erb_licker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Lick, I mean lint
        run: bundle exec erb_lint --lint-all

  fasterer:
    runs-on: ubuntu-latest
    needs: [test, bundler_auditor_cheeker_breeker, mr_brakeman, standard_english_mate_innit, erb_licker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: I am SPEED
        run: bundle exec fasterer

  rails_best_practices:
    runs-on: ubuntu-latest
    needs: [test, bundler_auditor_cheeker_breeker, mr_brakeman, standard_english_mate_innit, erb_licker]
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: I am SPEED
        run: bundle exec rails_best_practices

  reek:
    runs-on: ubuntu-latest
    needs: [test, bundler_auditor_cheeker_breeker, mr_brakeman, standard_english_mate_innit, erb_licker]
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Reek'n Roll
        run: bundle exec reek
