name: "Just flight CI"

on:
  pull_request:
  push:
    branches: [ "main" ]

env:
  RUBY_VERSION: 3.3.6
  RAILS_ENV: test
  BUNDLE_PATH: vendor/bundle

jobs:
# region test
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:latest
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: chairmansmap_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: rails
      PGPASSWORD: password
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Precompile assets
        run: bundle exec rails assets:precompile
      - name: Rspec with coverage
        run: COVERAGE=true bundle exec rspec --format documentation
      - name: Upload coverage report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
# end region test

# region security
  bundler_audit:
    runs-on: ubuntu-latest
    needs: [fasterer, rails_best_practices, reek]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Bundler audit
        run: bundle exec bundler-audit --update

  brakeman:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Brakeman
        run: bundle exec brakeman -q -w2
# end region security

# region lint
  standardrb:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Standardrb
        run: bundle exec standardrb

  erb_lint:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Erb lint
        run: bundle exec erb_lint --lint-all
# end region lint

# region code check
  fasterer:
    runs-on: ubuntu-latest
    needs: [standardrb, brakeman]
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Fasterer
        run: bundle exec fasterer

  rails_best_practices:
    runs-on: ubuntu-latest
    needs: [standardrb, brakeman]
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Rails best practices
        run: bundle exec rails_best_practices

  reek:
    runs-on: ubuntu-latest
    needs: [standardrb, brakeman]
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Reek
        run: bundle exec reek
# end region code check
